### ISSUE TITLE
Two Problem

### ISSUE THREAD

**Issue by ken147** [Bimmr/McInfected#101]
1:Sometimes players will disappear
2:Crackshot explosions will kill people even if i set 0damage

**Comment by Bimmr** [comment]
Not to sure what you mean by people disappearing, I need to know when, what
game state, what happened right before, etc.

That's a crack shot bug, I reported it to them about a year ago and they
haven't fixed it

**Comment by ken147** [comment]
That happened when player change kit

**Comment by Bimmr** [comment]
So they changed their kit and then they turn invisible?

**Comment by ken147** [comment]
is it that the shop addon removed?

**Comment by DeathJusty** [comment]
That sounds more like a minecraft issue

**Comment by Bimmr** [comment]
That would be correct, it is a minecraft issue. It happens when 2 or more
people all get teleported at the same time.  mcinfected does try and fix
this so I'm not to sure how to get it to happen because it doesn't happen
for me.

**Comment by DeathJusty** [comment]
It happened in 1.7, i don't know if the code was in there then but i had that problem

**Comment by Bimmr** [comment]
Minecraft 1.7?
