### ISSUE TITLE
Lobby Confusion

### ISSUE THREAD

**Issue by DeathJusty** [Bimmr/McInfected#102]
Hello again.

So i brought the plugin but im a little bit confused as to how the lobbies work now.
In the last version i played there was one lobby where players could vote on the maps they wanted to play and choose what kit to use, is there a way to set it up like that still or do i have to make seperate lobbies for each arena because i prefer voting system.

Cheers!

**Comment by DeathJusty** [comment]
Also sorry if this have been explained somewhere by you already, i had a quick look and couldnt find anything on that. i do see the vote commands still there but i cant find any documentation on as to how it works

**Comment by Bimmr** [comment]
1 Lobby - Multiple Arenas
People connect to the lobby, vote for an arena and the arena is played in that lobby.

You can have multiple Lobbies going at once that all have different/same arenas.

If you use "/McInfected Setup" it kinda walks you through making a lobby with arenas
