### ISSUE TITLE
Disguises

### ISSUE THREAD

**Issue by ken147** [Bimmr/McInfected#104]
How can i set the disguises more detail
such as  player <playername>
creeper setpowered

**Comment by Bimmr** [comment]
What disguise plugin are you using?

**Comment by ken147** [comment]
libsdisguise

**Comment by Bimmr** [comment]
Currently there is no way, due to the fact that all plugins except DisguiseCraft make it more difficult with the amount of possible tags in the game. I'll add it in the next version

**Comment by ken147** [comment]
Can you also add that the death msg can show the weapon name in the next version

**Comment by Bimmr** [comment]
I'll add support for the powered tag on creepers.
I'll add a way to show the weapon's name in the death messages.
There is no limit to how many kits, the GUI will just keep getting bigger, and if you have to many that you can't show them all then you should probably remove a few.

**Comment by Bimmr** [comment]
Added.

**Comment by ken147** [comment]
When will you finish the next version
