### ISSUE TITLE
problem of action bar   & also some issues

### ISSUE THREAD

**Issue by ken147** [Bimmr/McInfected#106]
-I'm using 1.8.8 spigot but it don't show the action bar even if I set action bar enable: true
-Can I use the custom sound for the sounds setting?
-Is it that I'm able to use weapon name for death msg and can set more detail for disguise now 
or I need to wait for the new version release?
-I also want to make the baby disguise

**Comment by Bimmr** [comment]
You'll have to wait for the new version, but as for the action bar, make
sure you have the latest BimmCore (or what ever I called it)

**Comment by ken147** [comment]
Im using bimmcore v0.0.6
is it correct?
Will the new version able to use the custom sounds?

**Comment by Bimmr** [comment]
In the config for mcinfected you should be able to set the sounds of
different events

**Comment by ken147** [comment]
I'm using the lastest BimmCore but the action bar is still not work

**Comment by Bimmr** [comment]
Is there an error or is it just not working?

**Comment by ken147** [comment]
It just not working

**Comment by Bimmr** [comment]
In the dev version Actionbar works. Custom sounds have already been implemented, and baby disguises have been fixed to work with LibsDisguise
