### ISSUE TITLE
Potion Bug

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#108]
I have a problem with the Potions. (1.10.2) Infected 1.4.3

I tried to add the potions in the game to classes like for example damage pools. The problem is now but when you are in the game it is always just normal water bottles filled with water. For drinkers, throwable and the new from the 1.9

**Comment by Bimmr** [comment]
How are you adding the potions? With the damage value or by creating custom
potions?

**Comment by MacTirom** [comment]
Ingame with /inf setup kits

**Comment by MacTirom** [comment]
Also normal minecraft potions.

**Comment by Bimmr** [comment]
K, I'll look into it

**Comment by Bimmr** [comment]
Due to the way 1.9 changed potions, it's not looking like I'll be able to get the power/duration from default potions. So I don't think there will be a way to fix this.

Until something tells me otherwise you'll just need to go into the actual config for potions.
