### ISSUE TITLE
Two potential bugs

### ISSUE THREAD

**Issue by DeathJusty** [Bimmr/McInfected#109]
Hello, I think i found a couple of bugs

1. I just noticed this error when launching the server http://pastebin.com/AJrNeEqh

2. I suspect it could be because of the spawn listener in essentials being set to high but sometimes when a player gets killed instead of being sent to a new spawn location they get sent to the server spawn area but are still in the gameand they drop all their armor and items. If they /suicide they are repawned back into the game but don't get their armor again. It also could be due to NoCheatsPlus, i have installed compactnocheatsplus but i have not used the plugin with anyone since. I can do some further testing if you need me to. I also have not seen any error code when the bug happens.

Keep up the great work :)

**Comment by Bimmr** [comment]
1. When I get time I'll look into it
2. Essentials would be taking over the respawn before mcinfected even sees
that the play had died.  try changing the priority.

**Comment by Bimmr** [comment]
If you're still using McInfected and having the essentials issue, would you be able to turn on debug mode(In config) then try and get the death thing to happen again then send me the server's log?

**Comment by DeathJusty** [comment]
I put it in debug mode and now it says theres no valid lobbies. this is whats happened in the console http://pastebin.com/b3WDxsaZ

**Comment by Bimmr** [comment]
What did you use to set the arena icon? /McInfected Setup ?

**Comment by DeathJusty** [comment]
none of my lobbies show up in game but the settings are there in the config files.
the icon part for all my arenas says !!me.bimmr.bimmcore.items.Items {}
is it possible that debug mode broke them in some way or another?

**Comment by Bimmr** [comment]
It's unlikely, but it was working before you turned on debug?

**Comment by DeathJusty** [comment]
Yeah, it was working before I loaded it into debug mode

**Comment by DeathJusty** [comment]
I took debug off at it still doesn't work anymore

**Comment by Bimmr** [comment]
It would be that the icon got changed, so you'll have back to a valid item.

**Comment by DeathJusty** [comment]
Could you please post the item line with a valid item in it so i know how to format the icon setting

**Comment by Bimmr** [comment]
You should be good to just use the setup command

**Comment by Bimmr** [comment]
Bugs from this ticket appear to be fixed
