### ISSUE TITLE
1.11 Conflicts

### ISSUE THREAD

**Issue by ericbarbwire** [Bimmr/McInfected#110]
Hey, I don't believe this plugin is compatible with 1.11
The issue with is that when 2 people join a game they both get kicked with the following message.
Attached Files:
http://imgur.com/a/9vTRm

**Comment by Bimmr** [comment]
Was there anything in the console before/after they got kicked?

**Comment by Bimmr** [comment]
Fixed in next update. Currently no ETA, but I can promise before the end of January.
