### ISSUE TITLE
Invisibility doesn't work

### ISSUE THREAD

**Issue by avsterbone** [Bimmr/McInfected#111]
So I'm trying to make it so everytime a player gets a kill they turn invisible for 10 seconds, but it doesn't seem to work. Here is the specific kit I'm trying to make:

  Phantom:
    Icon: item:20
    Inventory:
    - item:267
    Description:
    - '&bEver wanted to be invisible?'
    - '&bNot only do you get an &airon sword&b,'
    - '&bbut everytime you get a kill you turn'
    - '&ainvisible &bfor 10 seconds.'
    - '&bHowever, you have &cno armor&b.'
    KillStreaks:
      '1':
      - type:14 duration:10 amplifier:1
      '2':
      - type:14 duration:10 amplifier:1

There are no errors in console, but everytime a user with this kit gets a kill it says this in console:
[23:05:10 INFO]: Unknown command. Type "/help" for help.

If you could please fix this, or tell me what's wrong that'd be greatly appreciated.

**Comment by Bimmr** [comment]
Kill streaks reward items and commands so you would have to use something
like

"/effect <player>... "

**Comment by avsterbone** [comment]
Alright, that worked. I tried using commands like "/effect" for the potion options, but it didn't work. I then made this kit:

  Juggernaut:
    Icon: item:311
    Inventory:
    - item:267
    Armor:
      Helmet: item:Skull_Item data:2
      Chestplate: item:Leather_Chestplate color:16,120,43
      Leggings: item:Leather_Leggings color:16,120,43
      Boots: item:Leather_Boots color:16,120,43
    Potions:
    - potion:Strength,255,1
    - potion:Speed,255,2
    Transfer Potions:
    - potion:Blindness,10,1
    - potion:Slowness,10,10
    Description:
    - '&bYou get an &airon sword &band &aextra strength&b.'
    - '&bHowever, you respawn delay is &c10 seconds&b.'

However, the potions on it do not work. I am trying to make it so the zombie has Strength 2 & Speed 1 forever, but when they die and respawn they are frozen (slowness) and blind for 10 seconds. Please tell me what I did wrong in the kit, and if you could also fix that kit that would be greatly appreciated.

**Comment by Bimmr** [comment]
For the kits potions and transfer effects it knows to look for potions so
that's when you use the "type: time: power:" tag.  the reason it's
different is because those are potion effects while for items its potions

**Comment by avsterbone** [comment]
Alright, I have done what you said and got this:

  Juggernaut:
    Icon: item:311
    Inventory:
    - item:267
    Armor:
      Helmet: item:Skull_Item data:2
      Chestplate: item:Leather_Chestplate color:16,120,43
      Leggings: item:Leather_Leggings color:16,120,43
      Boots: item:Leather_Boots color:16,120,43
    Potions:
    - type:5 time:99999 power:1
    - type:1 time:99999 power:2
    Transfer Potions:
    - type:15 time:10 power:1
    - type:2 time:10 power:10
    Description:
    - '&bYou get an &airon sword &band &aextra strength &speed&b.'
    - '&bHowever, your respawn delay is &c10 seconds&b.'

However, only the regular potions work. The transfer potions do not work.

**Comment by avsterbone** [comment]
Bump

**Comment by Bimmr** [comment]
Can you send me your Kits.yml file.

**Comment by avsterbone** [comment]
I have sent you a PM on Spigot with it as I don't want it leaked.

**Comment by avsterbone** [comment]
Bump

**Comment by Bimmr** [comment]
It's odd that the blindness transfer effect works as where the other one doesn't...

**Comment by avsterbone** [comment]
I am using the latest version of both MC-Infected & BImmCore aswell as Spigot 1.8.8 https://i.gyazo.com/7309ad492d25691037cbf3c2e67043bd.png

**Comment by Bimmr** [comment]
Please never say you're using the "latest version" as that means almost nothing... Version numbers do matter.

**Comment by avsterbone** [comment]
Ok,

I am using Mc-Infected 1.4.3 https://i.gyazo.com/d93f637a13214d426bb9d86ea7e52fbe.png
I am using BimmCore v0.0.6
And I am using Spigot 1.8.8 https://i.gyazo.com/7309ad492d25691037cbf3c2e67043bd.png

Do you know what the issue is?

**Comment by Bimmr** [comment]
Currently no, I'll have to test to see if I can get the transfer effects to not work with those versions.

**Comment by avsterbone** [comment]
Bump

**Comment by Bimmr** [comment]
I'm not able to get the transfer effects to break. Try using a different effect instead of invisibility and seeing if it's still not working for you.

**Comment by avsterbone** [comment]
What? Invisibility was never the issue. The kit I quoted was the one that gave you blindness and slowness for 10 seconds.

**Comment by Bimmr** [comment]
I sent you a message over Spigot, just check that message out when you get time.

**Comment by Bimmr** [comment]
I'm assuming this is fixed?
