### ISSUE TITLE
players have all permissions

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#117]
```
permissions.yml:        - McInfected.Vote
permissions.yml:        - McInfected.Kit
permissions.yml:        - McInfected.Stats
permissions.yml:        - McInfected.kits.Assault
permissions.yml:        - McInfected.kits.Sniper
permissions.yml:        - McInfected.kits.Assassin
permissions.yml:        - McInfected.kits.Demoman
permissions.yml:        - McInfected.kits.Support
```
these are the only permissions I give in pex, yet any player that joins has full permissions for /mcinfected admin \<whatever\>

**Comment by Bimmr** [comment]
Ya I noticed that well I have been testing, for now just negate the
permission mcinfected.admin

**Comment by PhanaticD** [comment]
even after negating the node they still have full permissions

**Comment by Bimmr** [comment]
Hmm odd. I'll have to look into it.

**Comment by Bimmr** [comment]
Fixed in the dev version, turns out I had a " ; " in a place I didn't want...

**Comment by PhanaticD** [comment]
okay, please release soon its pretty much the only thing I am waiting on before opening the server
