### ISSUE TITLE
chat randomly breaking

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#121]
https://i.gyazo.com/1465b54acaf3b805c21fbdea4ee7da53.png

**Comment by Bimmr** [comment]
What chat plugin are you using?

**Comment by PhanaticD** [comment]
essentialschat

**Comment by Bimmr** [comment]
I'm still looking into this, it seems that at the end of a game the chat lags, but because the chat event is on a different thread then the game it goes even when other things don't, that's currently my only theory.

**Comment by Bimmr** [comment]
Are you using McInfected to format the chat in game? If so try to disable that then in the chat for the server you could add {RANK-PREFIX} to your current chat plugin's format.

**Comment by PhanaticD** [comment]
ok I will try
