### ISSUE TITLE
Rewards don't work

### ISSUE THREAD

**Issue by avsterbone** [Bimmr/McInfected#122]
In the config my "Reawrds" section reads this:

`  Rewards:
  - $100`

However, at the end of the game no money is awarded. I want it so the winning team gets $100 through vault's economy (/eco give <name> 100). Is there anyway to give the winners money through vault/commands?

**Comment by Bimmr** [comment]
Economy rewards worked in all my tests. Make sure you are using the propper version of Vault and the economy plugin you are using. If it still doesn't work then send me your config.yml and I'll check if theres anything wrong.

**Comment by avsterbone** [comment]
I am still having this issue. Here is my config: http://pastebin.com/55jS6uA0

and here is my Vault version https://i.gyazo.com/be6cd2a54b5d33759dbaa7db65706f0a.png

**Comment by Bimmr** [comment]
When you start up the server does McInfected say "Enabling Vault Economy"?

**Comment by avsterbone** [comment]
Yes, here is exactly what it says: http://pastebin.com/U8CZGti6

**Comment by Bimmr** [comment]
What economy plugin and what version are you using? I'll have to test with them as I was using Essentials(forget what version) and an older version of vault to test.

**Comment by avsterbone** [comment]
What version of Essentials & Vault are you using? Also, please link me to their downloads.

**Comment by Bimmr** [comment]
Vault: 1.5.3-b37
Essentials : TeamCity(2.x)

For links you'll need to find them yourself as I'm currently a little busy.
