### ISSUE TITLE
Random Kits being assigned

### ISSUE THREAD

**Issue by avsterbone** [Bimmr/McInfected#123]
Players are reported they are being given random kits ingame that they don't have access to. After further investigation here is what I have determined. If a player does not have permission to a certain kit(s) it will show as a red barrier block in the GUI and if they click it it simply won't give them access. However, if they do not select a kit that they have access before the game starts there is a random chance the user will be given a kit they shouldn't have access to. There are no wanrings/errors in console. I am using the same versions of everything as stated in this Github issue.

**Comment by avsterbone** [comment]
https://github.com/Bimmr/McInfected/issues/111

**Comment by Bimmr** [comment]
Odd, the code looks like everything is in order(Uses the exact same code as the GUI) Are you using the Ranks addon?

**Comment by Bimmr** [comment]
Fixed in dev version.... Had a bracket in the wrong spot...

**Comment by Bimmr** [comment]
Didn't mean to close...

**Comment by avsterbone** [comment]
Where is this dev version and is it compatible with 1.8.9?

**Comment by Bimmr** [comment]
Unfortunately I didn't fix this issue. I just had multiple tabs open and closed the wrong one.

**Comment by Bimmr** [comment]
By any chance was the kit being given to the player marked as the default kit in the config? I was finally able to get this to happen and by setting the kit I didn't have perms for as the default was the only way it was given to me.

**Comment by avsterbone** [comment]
I figured it out. I screwed up something in the config.

**Comment by Bimmr** [comment]
Ah well either way the default kits in the config will now require
permissions as well.
