### ISSUE TITLE
joining game but not being added

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#125]
players that log in to the server sometimes will be placed into the lobby area, and not the actual game going on. They are counted as humans though, which causes games to not end until time is up. This usually happens when there is higher number of players online, and seemingly randomly

**Comment by Bimmr** [comment]
Is there any error or anything in the console? Also if you are getting this bug, would you be ok to enable debug mode for McInfected then when it happens again send me the log?

**Comment by PhanaticD** [comment]
there was an error but it was truncated, it was the same nullpointer as the issues with this https://github.com/Bimmr/McInfected/issues/119
