### ISSUE TITLE
Lobbys.yml wrong icon

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#126]
The icon for the carnival map is a RANDOM item. I am lost as to how this is possible

in-game: https://i.gyazo.com/795db7aae6ff957c057910f7b8191914.png
Lobbys.yml http://pastebin.com/raw/52c83y8B

**Comment by Bimmr** [comment]
Did you set in manually or by using the setup command?

**Comment by PhanaticD** [comment]
the command caused it to be Icon: !!me.bimmr.bimmcore.items.Items {} and then after a server restart the game would not work, so I set it manually to be Icon: item:RAILS

**Comment by Bimmr** [comment]
That is very odd.... I can't tell for sure (im on mobile so it might format
a little funny ) but it looks like the alignment of
"Icon: items:Rail" might not be indented enough. It needs to match the
indentation of the "Description: ..."

**Comment by PhanaticD** [comment]
okay Ill try that

**Comment by Bimmr** [comment]
Fixed in dev version.... Had a bracket in the wrong spot...
