### ISSUE TITLE
Players losing health on game start

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#128]
when a player gets teleported from the lobby to a map for a new game, they lose three hearts

**Comment by Bimmr** [comment]
Are they being sufficated?

**Comment by PhanaticD** [comment]
no, it just happens immediately

**Comment by Bimmr** [comment]
That is very odd. Is there a specific map it happens on?

**Comment by PhanaticD** [comment]
from what i can tell no its random, it happens sometimes for players and sometimes not, regardless of map

**Comment by PhanaticD** [comment]
okay so most likely was entitycramming, after disabling that no one has said anything

**Comment by Bimmr** [comment]
Ok, just let me know if it starts back up.
