### ISSUE TITLE
stats not saving

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#131]
```
[18:26:34] [Craft Scheduler Thread - 227/INFO]: Unable to update stats, will try again in 5 seconds.
```
Just making an issue report for what we talked about in-game, i dont think it ever ended up actually updating 5 seconds later

**Comment by Bimmr** [comment]
So I've been working on trying to solve this and I think I have it solved, but it's hard to test something like this as it only happens on servers that have more users then I can test with.
