### ISSUE TITLE
Issue w/ ranks..

### ISSUE THREAD

**Issue by LostStories** [Bimmr/McInfected#133]
When I try to re-create ranks, or edit ranks or even do /mcinfected ranks I get this error.

04.03 16:52:50 [Server] INFO LostStories issued server command: /ranks
04.03 16:52:52 [Server] INFO LostStories issued server command: /rank
04.03 16:52:52 [Server] ERROR null
04.03 16:52:52 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcinfected' in plugin McInfected v1.4.4
04.03 16:52:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
04.03 16:52:52 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
04.03 16:52:52 [Server] INFO Caused by: java.lang.NullPointerException
04.03 16:52:52 [Server] INFO at com.bimmr.mcinfectedranks.Commands.RankCommand.execute(RankCommand.java:46) ~[?:?]
04.03 16:52:52 [Server] INFO at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?]
04.03 16:52:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 16:52:52 [Server] INFO ... 15 more

**Comment by LostStories** [comment]
04.03 17:04:15 [Server] INFO java.lang.NullPointerException
04.03 17:04:15 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetExpPrompt.acceptInput(SetExpPrompt.java:23) ~[?:?]
04.03 17:04:15 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:15 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
04.03 17:04:16 [Server] ERROR Error handling conversation prompt
04.03 17:04:16 [Server] INFO java.lang.NumberFormatException: For input string: "t"
04.03 17:04:16 [Server] INFO at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_25]
04.03 17:04:16 [Server] INFO at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_25]
04.03 17:04:16 [Server] INFO at java.lang.Integer.valueOf(Unknown Source) ~[?:1.8.0_25]
04.03 17:04:16 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetExpPrompt.acceptInput(SetExpPrompt.java:23) ~[?:?]
04.03 17:04:16 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.03 17:04:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]


ALSO ANOTHER ERROR I GET

**Comment by Bimmr** [comment]
The first error I am aware of and is currently fixed in the dev version, although that other error is because it expects a number when it asks for the exp, although I have made it so it will not give an error when an invalid input is given.

**Comment by LostStories** [comment]
Is there an ETA, on the dev version release?

**Comment by Bimmr** [comment]
Since i've recoded the whole damage system, I'm trying to test everything before I upload to spigot, but it's always hard to test combat. If you want the dev version you can message me over Spigot and I can send it to you, but just know that there may be some bugs.

**Comment by LostStories** [comment]
Alright I'll message you over spigot :) I can help and msg you any bugs that I find
