### ISSUE TITLE
Dev Version (of MCINFECTED)

### ISSUE THREAD

**Issue by LostStories** [Bimmr/McInfected#134]
So I updated, both of the plugins and got this new error

 06.03 20:19:07 [Server] INFO LostStories issued server command: /rank 06.03 20:19:07 [Server] ERROR null 06.03 20:19:07 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcinfected' in plugin McInfected v1.4.5 06.03 20:19:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25] 06.03 20:19:07 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25] 06.03 20:19:07 [Server] INFO Caused by: java.lang.NullPointerException 06.03 20:19:07 [Server] INFO at com.bimmr.mcinfectedranks.Commands.RankCommand.execute(RankCommand.java:46) ~[?:?] 06.03 20:19:07 [Server] INFO at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?] 06.03 20:19:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-f950f8e-0a81101] 06.03 20:19:07 [Server] INFO ... 15 more

 & I found another bug where the game does not end when both people are infected. I didn't want to create this on github, as I already had a thing open and I know this is a development build.

**Comment by Bimmr** [comment]
Can you send me your Ranks.yml?

**Comment by Bimmr** [comment]
Also what do you mean when both people are infected? Do you mean the last person died, or that someone joined then left? And if they died then how?

**Comment by LostStories** [comment]
I mean, like when all people are infected the game does not end, it continues. they also die by someone killing them, and I'll pm you the ranks.yml on spigot. :)

**Comment by Bimmr** [comment]
How did the person die? Melee? Falling? Projectile? Gun? Explosion? Other?

**Comment by LostStories** [comment]
Killed by another player

**Comment by LostStories** [comment]
If you have a Skype or something I could pm you on this would be way easier!

**Comment by Bimmr** [comment]
I do not have skype as last time I did someone gave it to a spam bot.

**Comment by LostStories** [comment]
any easier way to contact you?

**Comment by Bimmr** [comment]
Either this or Spigot

**Comment by LostStories** [comment]
Alright well, are you able to help me w/ these errors

**Comment by Bimmr** [comment]
Also you never did mention how the player died. Melee? Projectile? Crackshot Gun? Crackshot Explosion? Explosion?

**Comment by LostStories** [comment]
Meele.

**Comment by LostStories** [comment]
Basically the plugin generates errors, when I try to make new ranks or edit the old ranks, also can't edit how much xp it takes for someone to rank up I've tried everything

**Comment by Bimmr** [comment]
I'm not too sure what to tell you, i've tested and everything works fine for me. Make sure you've updated McInfected and all the add-ons, then delete the McInfected folder

**Comment by LostStories** [comment]
okay, I'll try to wipe every single thing and start over.

**Comment by LostStories** [comment]
Okay, so I wiped everything and I'm still getting the same error, am I able to get you on to help us? I can pm you the test servers ip.

**Comment by Bimmr** [comment]
At the moment I can't. But is there no other errors besides that first one? Because that error you posted is pointing to a line that would never cause an error... And I don't see how a player would get infected and the game not end unless there was an error.

**Comment by LostStories** [comment]
12.03 14:30:57 [Server] INFO LostStories issued server command: /McInfected setupnf Rank Private Prefix Set
12.03 14:30:58 [Server] ERROR Error handling conversation prompt
12.03 14:30:58 [Server] INFO java.lang.NullPointerException
12.03 14:30:58 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:30:58 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:30:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:30:59 [Server] INFO Gassy issued server command: /gmc
12.03 14:31:01 [Server] ERROR Error handling conversation prompt
12.03 14:31:01 [Server] INFO java.lang.NullPointerException
12.03 14:31:01 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:01 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:01 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:02 [Server] ERROR Error handling conversation prompt
12.03 14:31:02 [Server] INFO java.lang.NullPointerException
12.03 14:31:02 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:02 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:02 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:03 [Server] ERROR Error handling conversation prompt
12.03 14:31:03 [Server] INFO java.lang.NullPointerException
12.03 14:31:03 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:03 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:03 [Server] ERROR Error handling conversation prompt
12.03 14:31:03 [Server] INFO java.lang.NullPointerException
12.03 14:31:03 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:03 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:03 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:04 [Server] ERROR Error handling conversation prompt
12.03 14:31:04 [Server] INFO java.lang.NullPointerException
12.03 14:31:04 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:04 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:04 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:05 [Server] ERROR Error handling conversation prompt
12.03 14:31:05 [Server] INFO java.lang.NullPointerException
12.03 14:31:05 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:05 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:05 [Server] ERROR Error handling conversation prompt
12.03 14:31:05 [Server] INFO java.lang.NullPointerException
12.03 14:31:05 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.SetPrefixPrompt.acceptInput(SetPrefixPrompt.java:26) ~[?:?]
12.03 14:31:05 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
12.03 14:31:05 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
12.03 14:31:06 [Server] ERROR Error handling conversation prompt
12.03 14:31:06 [Server] INFO java.lang.NullPointerException

**Comment by LostStories** [comment]
I cant edit any ranks through in game or config
without iut generating an error

**Comment by Bimmr** [comment]
I've fixed the ranks addon, it can be downloaded fromthe Spigot chat

**Comment by LostStories** [comment]
13.03 23:36:53 [Server] INFO LostStories issued server command: /McInfected setupnf Rank LanceCPL HumanKit Set
13.03 23:36:55 [Server] ERROR Error handling conversation prompt
13.03 23:36:55 [Server] INFO java.lang.NullPointerException
13.03 23:36:55 [Server] INFO at com.bimmr.mcinfectedranks.Commands.Prompts.ChooseKitPrompt.acceptValidatedInput(ChooseKitPrompt.java:28) ~[?:?]
13.03 23:36:55 [Server] INFO at org.bukkit.conversations.ValidatingPrompt.acceptInput(ValidatingPrompt.java:26) ~[custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1066) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1186) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:749) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-f950f8e-0a81101]
13.03 23:36:55 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]


Generated this error. After I tried to pick a kit.

**Comment by LostStories** [comment]
Okay so when another player that is infected, that kills a player who is human, with a sword the game doesn't end properly, the time just keeps ticking down I don't know if this is on my end but yeah.

**Comment by Bimmr** [comment]
Can you turn on debug mode then send me the log next time it happens

**Comment by LostStories** [comment]
https://gyazo.com/076b330d49872416aedf12722a02a8b9

**Comment by Bimmr** [comment]
Ah, so you don't have crackshot?

**Comment by Bimmr** [comment]
The version in the dev folder should fix that issue

**Comment by LostStories** [comment]
Don't know if this is possible, but are you able to make a command or something where they do /ranks and it shows all the ranks they can achieve or earn?

**Comment by LostStories** [comment]
25.03 00:11:35 [Server] INFO LostStories issued server command: /McInfected Setup Shop
25.03 00:11:35 [Server] ERROR null
25.03 00:11:35 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcinfected' in plugin McInfected v1.4.5
25.03 00:11:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
25.03 00:11:35 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
25.03 00:11:35 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
25.03 00:11:35 [Server] INFO at me.bimmr.bimmcore.StringUtil.combineArgs(StringUtil.java:49) ~[?:?]
25.03 00:11:35 [Server] INFO at com.bimmr.mcinfectedshops.Commands.Setup.SetupShops.run(SetupShops.java:31) ~[?:?]
25.03 00:11:35 [Server] INFO at com.bimmr.mcinfected.Command.SetupCommand.execute(SetupCommand.java:100) ~[?:?]
25.03 00:11:35 [Server] INFO at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?]
25.03 00:11:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-7d78b81-d5e7885]
25.03 00:11:35 [Server] INFO ... 15 more

Also generated that error when I tried to setup shops.

**Comment by Bimmr** [comment]
Shops addon is no longer being worked on. I just forgot to remove it from the folder.
And as for showing all ranks, it'll have to wait because i'm currently working on revamping the setup menu.

**Comment by LostStories** [comment]
alright was just a suggestion! :)

**Comment by LostStories** [comment]
https://gyazo.com/5a05745c143bc762ee66160d927f49be another error

**Comment by Bimmr** [comment]
Just saying there was an error does almost nothing that helps me solve it... Try telling me what happened around the time the error occurred?

**Comment by LostStories** [comment]
https://gyazo.com/4d1d69b6f4e7c9904708e2a8496ac575 so this happens
when the timer runs out
and there's still a survivor
and the game doesn't end

**Comment by LostStories** [comment]
and are you able to give rewards on rankup? or like issue a command when a player ranks up

**Comment by LostStories** [comment]
https://gyazo.com/b4b4727845bd1c1bc24e6ebbfa7868fc

happened on startup

**Comment by LostStories** [comment]
https://gyazo.com/54f02901d8c0cc5508cd6f9626d076a8

Generates this error when one survivor is left, game doesn't end spams chat with "Player has won the game"

**Comment by LostStories** [comment]
or survived in this case

**Comment by Bimmr** [comment]
What version of minecraft are you running?

**Comment by LostStories** [comment]
1.11 latest stuff you put in the dev thing

**Comment by Bimmr** [comment]
You're running Minecraft 1.11? Because that error is saying your server doesn't have the glowing potion effect

**Comment by LostStories** [comment]
server is compatible with 1.7 1.8 1.11 and has protocol lib

**Comment by Bimmr** [comment]
That doesn't really answer my question as to what Minecraft version your
server is...
There is a difference between what version you're running at the versions
that can join you server...

**Comment by LostStories** [comment]
1.11 is the server version

**Comment by LostStories** [comment]
lol sorry didn't read the thing correctly

**Comment by LostStories** [comment]
are u able to make it so where the someone gets infected they don't just remain a zombie there but they have to respawn ?

**Comment by Bimmr** [comment]
I could add an option for it but I won't be able to do anything till the end of the month
