### ISSUE TITLE
(spigot version) copy items between maps

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#137]
when a round ends and you are a survivor, you pick up a gun so its on your cursor, and when you get teleported to the next game you can just place it back in your inventory. This allows you to carry items from one class to another for example getting guns as a zombie

**Comment by Bimmr** [comment]
I think I've fixed this, going to test it tomorrow to make sure. Just wanted to give an update so you didn't think I forgot about it.
