### ISSUE TITLE
Self view as a Zombies and makes it hard to kill anyone else

### ISSUE THREAD

**Issue by jsslcy** [Bimmr/McInfected#140]
Self view as a Zombies and makes it hard to kill anyone else.  

## What's Currently Happening

Self view as a Zombies and makes it hard to kill anyone else.  There is a command in LibsDisguise (/dvs) to toggle off and on self-viewing, but need a option in McInfected to keep self-viewing off.

----
## Your Environment
* Spigot Version used: 1.8.8
* McInfected Version: 1.4.4
* BimmCore Version: 0.0.7
* Any Addons?
- ProtocolLib-4.2.1
- Multiverse-Core-2.5.jar
- LibsDisguise 8.6.7
- McInfected-Ranks v1.2.1
- McInfected - Lobby Items v0.1.0
- ViaVersion-1.0.4.jar
- vault

**Comment by Bimmr** [comment]
Go into the LibsDisguise settings and change


# Shall the players view their disguises?
# Best used when viewing yourself in 3rd person
ViewSelfDisguises: true

To


# Shall the players view their disguises?
# Best used when viewing yourself in 3rd person
ViewSelfDisguises: false

**Comment by jsslcy** [comment]
Thanks!  I didn't see that earlier...sorry!

**Comment by jsslcy** [comment]
Also got a question about setting up knife throwing.  What's the best way to get in contact with you?

bought https://www.spigotmc.org/resources/throwing-weapons-1-8-1-9-1-10-1-11.5742/

**Comment by Bimmr** [comment]
There doesn't appear to be any API so I wouldn't be able to add support.
