### ISSUE TITLE
Feature Request: ping stage MOTD updating

### ISSUE THREAD

**Issue by jsslcy** [Bimmr/McInfected#141]
Feature Request:

PLEASE add the ping MOTD update to the stage of the game (Lobby / Pre Game / In Game)!!!
Needed to accurately pushed users to most filled Lobby or Pre Game of McInfected.

Add stages  (it could be Lobby, PreGame, Starting and e.t.c...);

(Using: OptimalTransfer - https://www.spigotmc.org/resources/optimaltransfer.19126/)

Please let me know, thanks!

**Comment by Bimmr** [comment]
I probably forgot to post this somewhere, but McInfected Dedicated has MOTD support

<img src="https://image.prntscr.com/image/d96fa068ca334b06ae78862c34b45faf.png">

**Comment by jsslcy** [comment]
Not sure why but it's not working.  Is there a placeholder or something I need in the server.properties file?  Can you please double check?

This is an example of what I'm looking for....
<img width="560" alt="motd" src="https://cloud.githubusercontent.com/assets/28246801/26525893/1b481e1a-4301-11e7-8e86-6ca588237f68.png">

**Comment by Bimmr** [comment]
you'll need <state> or <lobby> don't forgot the <>

**Comment by jsslcy** [comment]
Either I'm being retarded somehow or it's not working.  Can you come onto play.miniminecrafters.com on Minecraft and check/help me out? 

You're getting 5 star review either way.

**Comment by Bimmr** [comment]
I might be able to in a few minutes, I'll post either way,

**Comment by jsslcy** [comment]
Thanks!

**Comment by jsslcy** [comment]
**ThrowingWeapons was updated this morning....**

<img width="885" alt="tw_update" src="https://cloud.githubusercontent.com/assets/28246801/26532324/57a5a718-4399-11e7-8d61-b8f96aaf4b5d.png">

But still doesn't work.  Any suggestions I could give him?

**Comment by Bimmr** [comment]
It may work with the new way I've coded McInfected, although I'm still
testing things.

**Comment by jsslcy** [comment]
Any ETA on it's completion?

**Comment by Bimmr** [comment]
About 30 mins ago.
