### ISSUE TITLE
Players stuck in game

### ISSUE THREAD

**Issue by LordLagoon** [Bimmr/McInfected#144]
## What's Currently Happening

Whenever all of the players are infected on my server they are all still stuck in the map instead of the game ending.

----
## Steps to Reproduce (for bugs)

1. (for me) play any game

2.

3.

----
## Error Code
```
<!--- Please put the error in between the ``` tags -->  
No error code.
```

----
## Your Environment
* Spigot Version used:
* McInfected Version:
* BimmCore Version:
* Any Addons?(Include their versions, and DO NOT say newest

**Comment by LordLagoon** [comment]
Spigot - 1.11.2
McInfected - Latest
BimmCore - Latest

**Comment by Bimmr** [comment]
How many players are in the lobby?
Do they die during the infecting stage?
Do they die during the actual game?
Don't say "Latest"....

**Comment by LordLagoon** [comment]
2 Players are usually in the lobby, but it's happened with 3.
When they run out of human "hearts" they then turn into a zombie right away, but never have to re spawn. They do die during the actual game in the arena.

**Comment by Bimmr** [comment]
And there's no error at all?

**Comment by Bimmr** [comment]
I'm not able to replicate this. Please turn on debug mode and see if this happens again.

**Comment by Bimmr** [comment]
Closed because no response in 2 weeks, and unable to replicate
