### ISSUE TITLE
Can not create lobby join sign with custom sign addon 

### ISSUE THREAD

**Issue by aaa8881** [Bimmr/McInfected#145]
## What's Currently Happening

Can not create a lobby join sign if Custom Sign addon presents.

----
## Steps to Reproduce (for bugs)

1. Put McInfected and McInfected custom sign together. Make a working lobby and arena.

2. try to create lobby sign, lobby sign doesn't seem to be made.

3. try without custom sign addon, it works fine. 

----
## Error Code
```
<!--- Please put the error in between the ``` tags -->  

No error or exception are generated on sign create. It just doesn't work.

```

----
## Your Environment

* Spigot Version used: 1.10, 1.11 both tested
* McInfected Version: v1.5.0
* BimmCore Version: v0.0.8
* Any Addons?(Include their versions)
McInfected - Custom Sign v0.0.5
Server: CentOS 7

**Comment by Bimmr** [comment]
Seems to work for me.
Spigot 1.11.2/1.12
McInfected - 1.5.0
Custom Signs - 0.5
BimmCore - 0.8
<img src="https://i.gyazo.com/ff09ef01bd38d7189bd7f45c8cc6666b.gif">

Have you changed anything in the signs.yml?

**Comment by Bimmr** [comment]
Just re-read and noticed you said join sign, not status. I'll test it in a bit.

Edit: Just tested with command signs and they work with & without Custom Signs as well

**Comment by aaa8881** [comment]
![mcinfecte_1](https://user-images.githubusercontent.com/8253845/27672576-d46aad06-5cd6-11e7-9e92-423eabbf555e.PNG)
This shows some failures. I doubled checked and replace BimmCore with v0.0.8 and tested with spigot 1.11.2. I also removed sign.yml and regenerated with default one. Maybe this failure is problem?

**Comment by Bimmr** [comment]
Hmm, ya that looks like it's the issue. Not too sure why that would be
though...

**Comment by aaa8881** [comment]
I downloaded the latest BimmCore from spigot (which is v0.0.8) Maybe what you're using and what's upload in spigot are different?

**Comment by aaa8881** [comment]
umm I'm still waiting for your reply @Bimmr , I wanna get this worked. Have you checked the file? or can you suggest me to try things in other way?

**Comment by Bimmr** [comment]
I'm still trying to figure out why it breaks, it works perfectly fine on my end. For now, just don't use custom signs.

Please don't close and open the issue. It's like an unnecessary bump.

**Comment by Bimmr** [comment]
Download the new Custom Signs addon and let me know if that fixes it. It's a recompile to make sure everything exists as it expects it.

**Comment by aaa8881** [comment]
Thanks, it works well. Can you check Lobby Item addition as well? As you can see above pic, there's some error too, and it doesn't work now. Also, I didn't intentionally close and reopened but it was just an accident..

**Comment by Bimmr** [comment]
Try this: https://www.dropbox.com/s/09ei98vcsaim3xw/McInfected-LobbyItems.jar?dl=0
It was recompiled last night along with Custom Signs, I don't have enough time today to troubleshoot but see if that version fixes it. But if that doesn't work I'll look into it tomorrow.

**Comment by aaa8881** [comment]
Hey, sorry for late reply. been busy for something else. It's working fine.

**Comment by Bimmr** [comment]
Awesome, I guess I'll just upload it incase other people are having the
issue.
