### ISSUE TITLE
Error in Console for LobbyItems

### ISSUE THREAD

**Issue by xBMAN88** [Bimmr/McInfected#146]
I receive an error in console when the server starts for LobbyItems.

## What's Currently Happening
Started the server and I receive an error in the console and it's surronding the LobbyItems add-on, everything else seems to work fine.

----
## Steps to Reproduce (for bugs)

1. Start the server

2. Error appears in console

----
## Error Code
```
https://pastebin.com/dmhNfLQE - Happens at line 188


----
## Your Environment
* Spigot Version used: 1.8.8
* McInfected Version: 1.5.0
* BimmCore Version: 0.0.8
* Any Addons: LobbyItems: 0.1.0

**Comment by Bimmr** [comment]
Let me know if this version of LobbyItems fixes that error https://github.com/Bimmr/McInfected/issues/145#issuecomment-312903092

**Comment by xBMAN88** [comment]
I would just like to thank you for your quick response... you replied an hour after I opened the thread. The problem is fixed after downloading that jar. 

Once again, thank you. The plugin and support is most certainly worth the money.
