### ISSUE TITLE
Arenas command causes error.

### ISSUE THREAD

**Issue by SteveKitten** [Bimmr/McInfected#147]
I have just purchased this plugin and I believe that it looks amazing. Unfortunately I haven't gotten too far into setting ever thing up and I have run into an error.

## What's Currently Happening
Whenever I attempt to setup an arena (/mc setup lobby arenas), I receive a message that says that an internal error occurred. http://prntscr.com/ft6u7l
Whenever I try to go straight to creating an arena (/m setup lobby arenas createarena), the GUI shows up but has no real options. http://prntscr.com/ft6ush

----
## Steps to Reproduce (for bugs)

1. Run the plugin and check to see that all folders were created (from what I can tell, they are).

2. Use the create arena command.

3. Receive the error.

(I'm sorry if this isn't what you need, I'm not the best at this. If you need any other information just tell me please.)
----
## Error Code
`An internal error has occurred while attempting to perform this command``

----
## Your Environment

* Spigot Version used: 1.8.8
* McInfected Version: 1.5.0
* BimmCore Version: 0.0.8
* Any Addons?(Include their versions)
Nothing yet.

**Comment by SteveKitten** [comment]
https://github.com/Bimmr/McInfected/issues/1
I found this issue that was "resolved" but I believe that this is the error I am running into currently. (I know that one is hard to read and such, basically it doesn't show anything when trying to setup arenas. Thank you very much!

**Comment by Bimmr** [comment]
All you really posted was. 

"I had an error"

You need to actually post the error....

**Comment by SteveKitten** [comment]
If you check the screenshots you can see what the error says D: I'm sorry... I'll try to get what it says in the console.

**Comment by SteveKitten** [comment]
```
08.07 11:01:28 
[Server] INFO ... 15 more 08.07 11:01:28 
[Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?] 08.07 11:01:28 
[Server] INFO at com.bimmr.mcinfected.Command.SetupCommand.execute(SetupCommand.java:105) ~[?:?] 08.07 11:01:28 
[Server] INFO at com.bimmr.mcinfected.Command.Setup.LobbySetup.run(LobbySetup.java:47) ~[?:?] 08.07 11:01:28 
[Server] INFO Caused by: java.lang.NullPointerException 08.07 11:01:28 
[Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28
[Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77] 08.07 11:01:28 
[Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1.8.8_latest.jar:git-Spigot-21fe707-e1ebe52] 08.07 11:01:28 
[Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mc' in plugin McInfected v1.5.0 08.07 11:01:28 [Server] ERROR null
```

**Comment by Bimmr** [comment]
Why are you using such an old version of Minecraft?

**Comment by SteveKitten** [comment]
Because that is what the players I work with use. They don't like the newer versions. On the spigot page it says that it has been tested on 1.8? Is there a problem with it?
https://www.spigotmc.org/resources/mcinfected.2133/

**Comment by Bimmr** [comment]
It shouldn't be an issue; I was just curious.

**Comment by Bimmr** [comment]
It works for me, are you using a custom Spigot?
![image](https://user-images.githubusercontent.com/5053870/27987132-24af4770-63d7-11e7-9100-6dc67d2c2ce8.png)

**Comment by Bimmr** [comment]
I just noticed, the command you said you used isn't a valid command.
Don't try and type the commands, just use `/Mc Setup` then click to navigate.

You can also use `/Mc BSetup`

**Comment by SteveKitten** [comment]
http://prntscr.com/ft7hde
I have attempted to do /mc setup and I see that in your screenshot it looks a lot different for you.
http://prntscr.com/ft7hrx
http://prntscr.com/ft7hyo

As you can see it shows very little on my server compared to yours.
Also the first screenshot is showing that I use Spigot 1.8.8

**Comment by Bimmr** [comment]
Would I be able to hop on your server and try the setup?

**Comment by SteveKitten** [comment]
Sure! Thank you. I'll message you the server.

**Comment by SteveKitten** [comment]
Well idk how to direct message you and I don't really care so highrez.beastmc.com

**Comment by SteveKitten** [comment]
100/100 for support. Thank you so much for helping me with my dumb problem! Have an amazing day!
