### ISSUE TITLE
Game doesn't close after all infected

### ISSUE THREAD

**Issue by Ostler** [Bimmr/McInfected#149]
## What's Currently Happening

The game won't close after everyone is infected. The timer just keeps going and says 'Humans' win or whatever.

----
## Steps to Reproduce (for bugs)

1. Start game

2. Play, have the infected infect all on new version.

3. Wait for the timer.

----
## Error Code
```
<!--- Please put the error in between the ``` tags -->  

```

----
## Your Environment

* Spigot Version used:
* McInfected Version:
* BimmCore Version:
* Any Addons?(Include their versions)

**Comment by Bimmr** [comment]
Information not given, if you can't take the time to give me the information I ask for, I'm not going to take the time to troubleshoot a bug I'm not going to be able to replicate.

**Comment by Ostler** [comment]
I'm sorry, I never even released the 'Your environment'. 
Spigot Version used: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) 1.8.8-R-.1-SNAPSHOT
McInfected Version: v1.5.0
BimmCore Version: 0.0.8
Any Addons?(Include their versions): McInfectedRanks (But it was doing it before I added this) Version 1.2.2

Sorry if you thought I was lazy. I really need this fixed. I'll give you any other info.

**Comment by Ostler** [comment]
and there is no error, it simply doesn't work.

**Comment by Bimmr** [comment]
How many people do you have in the lobby?

**Comment by Ostler** [comment]
It originated with 2, so I brought more people, brought up to 9 people and it still didn't work.

**Comment by Bimmr** [comment]
K, and how is the last human dieing? Falling, Crackshot guns, melee, bow, etc?

**Comment by Ostler** [comment]
Sword, just like normal

**Comment by Ostler** [comment]
I don't even have crackshot installed.

**Comment by Bimmr** [comment]
Turns out not having crackshot is what's causing the issue. I'll have it fixed and uploaded before this weekend(hopefully).

**Comment by SteveKitten** [comment]
I'd just like to say that you're right, when I got crackshot it ended but before that it wasn't.

**Comment by Ostler** [comment]
Alright

**Comment by Ostler** [comment]
Thanks

**Comment by Bimmr** [comment]
Fix has been uploaded to Spigot. If it turns out that it isn't just reopen/post on the ticket.
