### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by aaa8881** [Bimmr/McInfected#150]
1. Leave item addition in lobby item addon.
Not everyone wants to type command . It might be nice to have a leave menu that user can click and leave.

2. option to not start game automatically after game is done 
Here too, so many people in my server complained about this lol. Ofc you can say "well you can just leave via command", but this is hard to expect 10 year old kid to voluntarily look up command to do that. Some people might just wanna play one game and leave, so this option might be helpful.

3. some better explanation on default kit
It's definitely very helpful to link miencraft wik ( no sarcasm ) ,  but it will be even better if you explain what exactly does each kit line does - especially when it comes to enchantment and potion. Also it'll be extremely helpful if there is example of multiple enchantments. Ofc plugin users need to learn something, but not necessarily learn in hard way. This suggestion will no longer help me as I read and tried out enough, but future customers might thank you for better explanation if there is any. 

4. Command execution option for other events 
such as "on game start" , "when zombie kill human" , "when "human kills zombie" , when "game ends" etc.. yes I know there is API, but not everyone knows how to use that, and you can be more generous and provide these options so that everyone can use it more easily. 

That's it. Thanks!

**Comment by Bimmr** [comment]
1. You can make a leave item using the Lobby Items addon
2. As stated above you can make a leave item with the Lobby Items addon
3. https://github.com/Bimmr/McInfected/wiki/McInfected---Wiki-Home#kits
4. It is something that has been requested, and is on my list
