### ISSUE TITLE
Want to edit some things inside MCInfected

### ISSUE THREAD

**Issue by GarthVadar** [Bimmr/McInfected#153]
I bought the MCInfected plugin, but I wanted to change things up a bit. May I have the source? Thanks

**Comment by Bimmr** [comment]
Feel free to decompile an edit the code to your liking. A few people have already done so, so I'd imagine it's not too difficult to fix up after you decompile.

**Comment by ghost** [comment]
@Bimmr using JD-GUI, it's not easy to fix after decompiling. There's just error after error and it's quite tedious - half of the code is just unknown objects and errors that JD-GUI just can't get.

I'm planning on making a system for @NightWolff9, but it would just save me loads of time and hassle on trying to fix the endless errors if I had the source. I would also be happy to contribute to the project if I see anything that can be improved.

**Comment by Bimmr** [comment]
I'm sorry but I don't give out the source. I've done it once and the guy turned around and leaked it. So it's a case of one person ruined it for everyone.

**Comment by ghost** [comment]
Hmm, okay. My desire is to simply add a prestige system to the plugin for NightWolff, but I presume your stance on this matter won't change. Thank you anyways! :)

**Comment by Bimmr** [comment]
Using the ranks addon you can simulate a prestige system, the ranks are
made in a way to allow different branches, so you would be able to use
that.

There is also an API for McInfected, I need to finish the page for it
though.

**Comment by Bimmr** [comment]
@AthenaDev If you need any API added to either McInfected or McInfected Ranks, feel free to ask.
