### ISSUE TITLE
Infected voting

### ISSUE THREAD

**Issue by SpecterPanda** [Bimmr/McInfected#155]
so a question I have, is there anyway instead of having voting we could have a map rotation? It is a serious question saying players  always vote for the same maps. If  we have a map rotation custom rotation or not it would solve that problem

**Comment by Bimmr** [comment]
One thing that you can do is prevent voting, it will choose a random arena.

**Comment by SteveKitten** [comment]
We like the idea of voting, but would rather have it so that it will prevent you from choosing the past maps until they have all been played.

**Comment by Bimmr** [comment]
Trying to add something like that would break a good portion of McInfected,
so I'm not going to be able to add anything like that.

**Comment by SteveKitten** [comment]
Okay, thank you for your help either way.
