### ISSUE TITLE
Killstreaks, /mc bsetup, and kill assists

### ISSUE THREAD

**Issue by SteveKitten** [Bimmr/McInfected#159]
Killstreaks don't seem to work.
/mc bsetup says internal error.
We would like to request "kill assists" so that people stop complaining about kill steals.

## What's Currently Happening
When I make my way to where you would usually setup killstreaks, there is no options.
http://prntscr.com/ggnfzu

When I do /mc bsetup and try to manage anything, it says "An internal error occurred while attempting to perform this command" http://prntscr.com/ggngqp

People are mad about kill stealing so we'd like there to be a new stat for assists.

----
## Steps to Reproduce (for bugs)
1. /mc setup

2. Click on kits.

3. Click on any of the kits.

4. Click on killstreaks.

5. No options for killstreaks. http://prntscr.com/ggnfzu

1. /mc bsetup

2. Click on manage <anything>

3. It says "An internal error occurred while attempting to perform this command" http://prntscr.com/ggngqp

----
My console is currently being spammed by stuff and I can't find the error code, I apologize. I'll get it as soon as I stop the spam.

----
## Your Environment

* Spigot Version used: 1.8.8
* McInfected Version: 1.5.2
* BimmCore Version: 0.0.8
* Any Addons?(Include their versions)
Ranks: 1.2.4
Custom Signs: 0.0.6
Lobby Items: 1.0.0
Leaderboards: 0.1.1

**Comment by Bimmr** [comment]
Assists are something I've thought about adding but never gotten around to it. As as for the killstreaks and BSetup, I'll need that error code before I can start doing anything.

**Comment by SteveKitten** [comment]
/mc bsetup
03.09 15:55:39 [Server] INFO at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?]
03.09 15:55:39 [Server] INFO at com.bimmr.mcinfected.Command.BSetupCommand.execute(BSetupCommand.java:102) ~[?:?]
03.09 15:55:39 [Server] INFO at com.bimmr.mcinfected.Command.BSetup.LobbyBSetup.run(LobbyBSetup.java:178) ~[?:?]
03.09 15:55:39 [Server] INFO at com.bimmr.mcinfected.Command.BSetupCommand.addFooter(BSetupCommand.java:65) ~[?:?]
03.09 15:55:39 [Server] INFO Caused by: java.lang.NoSuchMethodError: me.bimmr.bimmcore.messages.FancyMessage.toPlainText()Ljava/lang/String;
03.09 15:55:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]


There is no console anything when I go into killstreaks.

**Comment by SteveKitten** [comment]
Also McInfected.Vote.x3 - x5 only gives 2 votes.
I have checked so many times to make sure the permissions are correct, but it still only gives 2 votes.

**Comment by Bimmr** [comment]
Make sure you are using a BimmCore that is up to date, as the error is saying that a function doesn't exist.

I'll look into the voting perms when I get a chance.

**Comment by SteveKitten** [comment]
My BimmCore is up to date.

**Comment by Bimmr** [comment]
Have you used /reload at all?

**Comment by SteveKitten** [comment]
Never. I always stop the server or reload plugins individually with their intended command.

**Comment by SteveKitten** [comment]
Any update?

**Comment by Bimmr** [comment]
Currently, with class and my job, I don't have time currently to work on
plugins.

**Comment by SteveKitten** [comment]
Okay, I understand. I appreciate the help you have done for us so far ^_^

**Comment by SteveKitten** [comment]
Hey Bimmr, I am opening my server again soon and I have been trying to add Killstreaks again. From what I see on this issue: https://github.com/Bimmr/McInfected/issues/118, you have an example of a kit with a Killstreak in it as seen below.
http://prntscr.com/jdfdbf
I have tried to add things in this way to my kits in game but have had no luck with getting it working. If you could show me the correct way I'd be very happy!

**Comment by Bimmr** [comment]
Thank you for mentioning this, a few versions ago the way Killstreaks got changed was to allow a list, and I forgot to change the image.

So the new way would be this: 
![image](https://user-images.githubusercontent.com/5053870/39608095-1adc1350-4f0d-11e8-83a4-206426311255.png)

**Comment by SteveKitten** [comment]
I will test this and get back to you, thank you so much!

**Comment by Bimmr** [comment]
I finally have a lot more free time so if you notice anything that needs to
be fixed/changed just let me know.

**Comment by zoltanbi** [comment]
Hey I was looking for a thread about killstreaks, a question I have is can I make it so that the kill streak message appears after each kill instead of every 5th kill? Cheers!

**Comment by Bimmr** [comment]
I suppose I could just make it configurable

**Comment by zoltanbi** [comment]
That would be awesome 👍

**Comment by Bimmr** [comment]
@SteveKitten The killstreak setup command has been fixed, although I strongly recommend you use **/McInfected BSetup** instead

@dllpickle Killstreak notifications will be configurable in the next version

**Comment by zoltanbi** [comment]
Sweet 👍
