### ISSUE TITLE
McInfected doesnt load on startup and player respawn glitch

### ISSUE THREAD

**Issue by LadyHaley** [Bimmr/McInfected#161]
## What's Currently Happening

1. When I start my server I get the error code listed below and the plugin doesn't load. If I use plugman to load the server after the fact it loads up fine.

2. Another bug I get which I believe was brought to your attention before is a respawn bug. when players are killed they have a chance of dropping all their things and respawning at the spawn area. I set essentials respawn priority to low and it just sent them to the arena worlds spawn area. If they do '/mcinf suicide' they respawn back into the arena with their kit but they have no disguise and it just happened again. Not sure whats causing that, I disabled everything that interacts with player combat. There are no bugs output when this happens

----
## Steps to Reproduce (for bugs)

1. Start server up, plugin doesn't load

2. Kill players until bug happens

3.

----
## Error Code
`03.12 11:37:09 [Server] INFO Enabling McInfected v1.5.2
03.12 11:37:09 [Server] INFO -----=========[[ McInfected ]]=========-----
03.12 11:37:09 [Server] INFO Loaded Lobby: Lobby
03.12 11:37:09 [Server] INFO ----- Loaded Arena: Grind
03.12 11:37:09 [Server] INFO ----- Loaded Arena: Carrier
03.12 11:37:09 [Server] INFO ----- Loaded Arena: Plaza
03.12 11:37:09 [Server] ERROR Error occurred while enabling McInfected v1.5.2 (Is it up to date?)
03.12 11:37:09 [Server] INFO java.lang.NullPointerException: null
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.Lobbys.Lobby.updateSigns(Lobby.java:454) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.Lobbys.Lobby.setGamestate(Lobby.java:167) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.Lobbys.Lobby.<init>(Lobby.java:58) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.Lobbys.LobbyManager.createLobby(LobbyManager.java:30) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.Lobbys.LobbyManager.loadLobbysFromFile(LobbyManager.java:151) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.Lobbys.LobbyManager.<init>(LobbyManager.java:25) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.McInfected.reload(McInfected.java:171) ~[?:?]
03.12 11:37:09 [Server] INFO at com.bimmr.mcinfected.McInfected.onEnable(McInfected.java:271) ~[?:?]
03.12 11:37:09 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [custom.jar:git-Spigot-5695bca-53fccdf]
03.12 11:37:09 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]``
  

```


----
## Your Environment
<!--- If you say latest, or newest your ticket will be deleted. No Exceptions -->
* Spigot Version used: CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT
* McInfected Version: v1.5.2
* BimmCore Version: v0.0.8
* Any Addons?(Include their versions)

**Comment by Bimmr** [comment]
Try deleting your Signs.yml or just deleting everything in it. It looks
like it cant update the lobby signs.

**Comment by Bimmr** [comment]
As for the respawn bug it only happens when essentials is on the server,
and it is random when it happens. I'll see what i can do though. Been
looking for a reason to work on McInfected, just havnt had time to work on
new things.

**Comment by LadyHaley** [comment]
There is no signs.yml
the respawn glitch is making the game somewhat unplayable for my server since it happens almost every match

**Comment by LadyHaley** [comment]
Is there a download to a default signs.yml i could use to try and fix the error code issue

**Comment by Bimmr** [comment]
To fix the signs, try opening the Lobbys.yml and removing the signs from the lobby. I was hoping to get time to add a fix into the code, but classes are making it hard to find time to fix McInfected. Hopefully I will have time either this week or weekend. And I'll look into the essentials bug when i get time aswell.

Example Lobbys.yml:

```
MyLobby:
  Location: ...
  Signs:
    Information:
      - ...
      - ...

```

Change it to:


```
MyLobby:
  Location: ...
```

**Comment by LadyHaley** [comment]
I removed the signs from the world and then made sure they were no longer in the config, the plugin then loaded up normally so i figured it was fixed but then I made new signs and it started not loading again
https://pastebin.com/xcGZ49zK

**Comment by Bimmr** [comment]
I finally have time to work on McInfected... Are you able to send me your Lobbys.yml and the name of your world folder?

**Comment by LadyHaley** [comment]
Here is the Lobbys.yml file https://pastebin.com/7uj1nU3G
The world the lobby and signs are in is HUB and the world the arenas are in is world_arenas

**Comment by LadyHaley** [comment]
The plugin not loading on startup is manageable, the massive respawn bug is whats really preventing me from being able to enjoy the game since i encounter the bug 90% of the time

**Comment by Bimmr** [comment]
If I send you a version could you test it to see if it fixes the issue?

**Comment by LadyHaley** [comment]
Absolutely. Add me on Discord so you can send the test build over LadyHaley#5130

**Comment by LadyHaley** [comment]
Would you still like me to try the test version?

**Comment by Bimmr** [comment]
Yes, just been busy this week. I can send it on Saturday

**Comment by Bimmr** [comment]
Can't seem to find you on discord, try finding me: Bimmr#0258

**Comment by LadyHaley** [comment]
Request sent
