### ISSUE TITLE
Setting up lobby

### ISSUE THREAD

**Issue by Sillysheep165** [Bimmr/McInfected#162]
I am unable to set up a lobby using a chat command. We have global chat and when you enter the name of the lobby it just appears in chat and doesn't set a lobby. 

Is there anyway you can give me a sample lobby.yml so I can manually set.

**Comment by Bimmr** [comment]
I never thought about how some chat plugins would handle conversations, I
should probably add a way around that. But here you go.
https://pastebin.com/NRUVXE4i

**Comment by Bimmr** [comment]
I finally have some free time. I will try and make it so the commands can be used without the prompts.
