### ISSUE TITLE
McInfected got bugged

### ISSUE THREAD

**Issue by eric2788** [Bimmr/McInfected#165]
## What's Currently Happening

1.scoreboard disappeared while countdown to start the game
2.sometimes it has no time limited while in game[even the countdown doesn't display on scoreboard]
3. EXP level countdown disappeared
4. Potions Effects of health boost doesn't have amplifier
5. one of the kit inventory only can load two things
----
## Steps to Reproduce (for bugs)

1.start the game

2.scoreboard disappeared while countdown

3.no time limited while in game

4.EXP level countdown disappeared

----
## Error Code
```
<!--- Please put the error in between the ``` tags -->  
1. https://pastebin.com/KSJwBdxM
2. https://pastebin.com/JjMYJ7vV
```

----
## Your Environment

* Spigot Version used: 1.12.2
* McInfected Version: 1.5.2 
* BimmCore Version: 0.0.8
* Any Addons?(Include their versions)
McInfected dedicated 0.1.7
McInfected Ranks 1.2.4
McInfected LobbyItems 1.0.0
McInfected leaderboards 0.1.2

----
##My plugins list
![default](https://user-images.githubusercontent.com/6276840/37863514-18dc6ee8-2f9a-11e8-9b0c-7c86b54a7b74.png)

----
##my settings
https://drive.google.com/open?id=1SeBJbrWW52yUs9PtwKVYaMx6Lgp6b24N
and i have make sure my gun:<name> is all matching crackshot guns yml

**Comment by Bimmr** [comment]
One thing that is causing an issue is that rank prefixes' have a max of 16
characters, so it's cutting off your prefix then saying to matches
preexisting prefix, as for the item error I'll have to do some debugging

**Comment by eric2788** [comment]
well i have fixed the rank prefix error problem
and have found that the health scale didn't change was caused by another plugin
but the problem of exp countdown, item null and prestart scoreboard disappeared is still existing

**Comment by eric2788** [comment]
ok now item null error fixed by one capital letter
remain the problem of exp countdown and prestart scoreboard disappeared
and these bug have no error so I don't know what should do now.......

**Comment by eric2788** [comment]
got it , there are no prestart scoreboard (only votemap scoreboard) and exp countdown.......sorry
because it has before so i think that's a bug.....
however, i have an suggestion
Could we translate this:
![default](https://user-images.githubusercontent.com/6276840/37873307-bf8da6f0-304c-11e8-8f84-276099825a20.png)

**Comment by Bimmr** [comment]
Translations are something that keeps getting asked, so when I have time I
will add that.

**Comment by eric2788** [comment]
thx, you are really so nice!
I think this thread can be closed :3
