### ISSUE TITLE
Voting GUI Error

### ISSUE THREAD

**Issue by xBMAN88** [Bimmr/McInfected#166]
Version 1.5.5
## What's Currently Happening

When you add more than 16 maps to the vote GUI, the GUI attempts to exceed 6 rows.

----
## Steps to Reproduce (for bugs)

1. Add more than 16 maps to a lobby.

2. Use /vote

3. See image below for result.
![image](https://user-images.githubusercontent.com/8965862/41040026-3957d28a-6969-11e8-85da-93a12b2ed966.png)

----
## Error Code
```
<!--- Please put the error in between the ``` tags -->  

```

----
## Your Environment

* Spigot Version used: 1.8.8
* McInfected Version: 1.5.5
* BimmCore Version: 0.0.8
* Any Addons?(Include their versions)

**Comment by Bimmr** [comment]
I never once thought someone would have more than 15 Arenas in a single
Lobby, I will see what I can do.

**Comment by Bimmr** [comment]
My only suggestion, for the time being, is to use multiple lobbies or reduce the number of arenas you have.

**Comment by SteveKitten** [comment]
I'd like this to be fixed as well. I have 33 maps currently with more coming very soon. http://prntscr.com/k6ponz
![download 1](https://user-images.githubusercontent.com/30003983/42735843-46390b98-8810-11e8-992a-6f5283db8c8f.png)

**Comment by Bimmr** [comment]
the issue is that it is a Minecraft issue, and so I would have to
implement pages which would be a major recode of the way I handle inventory
menus. So it's not currently something I'm planning on doing yet. (But I am
slowly working on it)

**Comment by SteveKitten** [comment]
Just so you know, other users have this problem as well. My server currently has 33 maps and many more that aren't being used because of this. https://prnt.sc/k6ponz
![download 1](https://user-images.githubusercontent.com/30003983/42736145-e0257426-8815-11e8-8ac3-63d582c444c3.png)

**Comment by Bimmr** [comment]
--Snip
Almost got it.

**Comment by Bimmr** [comment]
4AM in the morning, but I had some good music playing and didn't notice the time until just now.
<a href="https://gyazo.com/1befbea87b2c9adb1320126f5eda29e7"><img src="https://i.gyazo.com/1befbea87b2c9adb1320126f5eda29e7.gif" alt="Image from Gyazo" width="368"/></a>

**Comment by Bimmr** [comment]
If you want to test it(I need some people to stress test), send me a msg over discord.
https://discord.gg/FwmAtD
