### ISSUE TITLE
Disguises with armors

### ISSUE THREAD

**Issue by cpstest-tech** [Bimmr/McInfected#175]
## What's Currently Happening
When someone has an infected kit, their armor shows.

----
## Steps to Reproduce (for bugs)
Just create an infected kit with an armor and a disguise, it shows the armor on the zombie.

## Error Code
there is not an error
----
## Your Environment
* Spigot Version used: 1.12.2 
* McInfected Version: 1.6.7
* BimmCore Version: 1.0.7
* Any Addons?(Include their versions)
IDisguise 5.8.2
McInfected-Dedicated v0.2.1
McInfected - Lobby Items v1.1.1
Vault 1.5.6

**Comment by Bimmr** [comment]
Depending on the disguise plugin your using you can probably turn that off

**Comment by cpstest-tech** [comment]
That is IDisguise, how to disable it?

**Comment by Bimmr** [comment]
Check the config file. If there isn't an option then try LibsDisguise.

**Comment by cpstest-tech** [comment]
LibsDisguise is only for 1.8

**Comment by Bimmr** [comment]
On their spigot page:
*Supports: *1.12, 1.13, 1.14, 1.15, 1.16

**Comment by cpstest-tech** [comment]
I see, but it had the issue of being behind players and blocking their hits

Il dom 14 mar 2021, 19:48 Randy ***@***.***> ha scritto:

**Comment by Bimmr** [comment]
- Showing/Hiding Armor
- Showing/Hiding disguise while in disguise

Both of those are options that can be changed depending on the disguise plugin you're using. If you need support for that you will need to go to their support pages. Neither are McInfected bugs/issues.
