### ISSUE TITLE
How to add terracotta or concrete

### ISSUE THREAD

**Issue by cpstest-tech** [Bimmr/McInfected#176]
Hello guys, I am trying to set terracotta and concrete in kit icons, when i try to add terracotta it shows up as ? head, if I use concrete it just doesn't show up

**Comment by Bimmr** [comment]
For support please use discord. GitHub is more for issues/bugs.

**Comment by cpstest-tech** [comment]
where is the discord?

**Comment by Bimmr** [comment]
You'll find it on the spigot page. I don't have a link handy atm.
