### ISSUE TITLE
Got this error with Ranks addon

### ISSUE THREAD

**Issue by xBMAN88** [Bimmr/McInfected#27]
I bought the ranks addon and received this error when trying to do /rank

http://pastebin.com/NJMmiYnC

**Comment by Bimmr** [comment]
This is an issue Ive fixed in the latest version. Although seeing as your not using 1.8.3 it'll be a little bit before I have time to make the next update work for 1.8.3 and older

**Comment by xBMAN88** [comment]
I would be using the latest version, however in a previous issue, MCInfected Core doens't work for 1.8.3

**Comment by Bimmr** [comment]
Sorry, by latest I mean the version I'm currently doing a few tests on
