### ISSUE TITLE
Im not able to see the Zombie

### ISSUE THREAD

**Issue by iFluzzer** [Bimmr/McInfected#28]
Hello, the zombie is completely invisible to me, i tried with libs disguise and disguisecraft, also using spigot 1.8

**Comment by Bimmr** [comment]
Are you able to see disguises when you use the disguise plugin's
commands?(Outside of McInfected)

**Comment by iFluzzer** [comment]
Its weird cuz he can see me when im zombie, but i cant see him when he are

**Comment by Bimmr** [comment]
And this is happening outside of McInfected aswell?

**Comment by iFluzzer** [comment]
Not tested yet

**Comment by iFluzzer** [comment]
Cant see him out of the game too...

**Comment by Bimmr** [comment]
Then that would be the disguise plugin's bug. Is your protocollib and
disguise plugin both the right version for your server?

**Comment by iFluzzer** [comment]
Yes i think, can u send me plz? for 1.8

**Comment by Bimmr** [comment]
1.8.3?

**Comment by iFluzzer** [comment]
1.8.1

**Comment by Bimmr** [comment]
Do u use libs disguise or disguisecraft?

**Comment by iFluzzer** [comment]
libs

**Comment by iFluzzer** [comment]
its for 1.8.3 im sorry

**Comment by Bimmr** [comment]
http://www.spigotmc.org/resources/libs-disguises.81/download?version=18930
http://ci.shadowvolt.com/job/ProtocolLib/lastSuccessfulBuild/artifact/ProtocolLib/target/ProtocolLib.jar

Both the latest versions of each

**Comment by iFluzzer** [comment]
these are for 1.8.3?

**Comment by iFluzzer** [comment]
I still cant see them, but they can see me when im disguised, no errors on console at all

**Comment by iFluzzer** [comment]
Nevermind, changed to minecraft 1.8.3 and working fine
