### ISSUE TITLE
Server crash after virus release in 1.8.3

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#30]
Hi

I have updated my server to 1.8.3 and McInfected to 1.1.9. Also, I use LibsDisguises 8.3.1 and ProtocolLib 3.6.3.

Players can join an arena, but immedialty after the virus is release, the server crash...

Error log : http://pastebin.com/56BXvXsY

Thanks

**Comment by Bimmr** [comment]
I cant find anything in that error to do with McInfected, try sending it to
spigot to see if they have any ideas

**Comment by JohOply** [comment]
Done :)

https://hub.spigotmc.org/jira/browse/SPIGOT-877
