### ISSUE TITLE
Ranks are not saving

### ISSUE THREAD

**Issue by DarkRaider462** [Bimmr/McInfected#31]
Each time the server restarts, each progress for a rank gets reset.
And Ranks in general are bugged for me.

**Comment by Bimmr** [comment]
Do you save to files or MySQL

**Comment by DarkRaider462** [comment]
Files. I do not use MySQL yet

**Comment by Bimmr** [comment]
Do they reset after a game? When the play leaves? After a server restart?
And what do you mean by "ranks in general are bugged" as that statement
does nothing in terms of helping me fix what ever issue it is

**Comment by Bimmr** [comment]
Closed because there was no response.
