### ISSUE TITLE
Default rank?

### ISSUE THREAD

**Issue by DarkRaider462** [Bimmr/McInfected#32]
I didn't find it on the wiki or plugin page on spigot. But when people join, they need to always select a kit. Is it possible to set a kit by default? So that everyone has the kit when they join.

And another fun thing to add, is to save the kit that they had last game, and use that kit for next round.

If this is already added, i'm sorry, i don't have much time to search how.

**Comment by Bimmr** [comment]
Default kits can only be assigned using Ranks. And they should stay the
same kit between rounds its when they join and leave it chooses a random one

**Comment by DarkRaider462** [comment]
Ranks? As in groupmanager ranks? Or MCInfected-Ranks.
If it's groupmanager, do i just give them the permission for a single kit?

**Comment by Bimmr** [comment]
It would be the ranks addon for McInfected

**Comment by DarkRaider462** [comment]
Is there really no other way? Like have a 3rd party plugin handle login commands? And let it automaticly choose a kit?
Because the ranks addon does not work for me, and i already have another plugin dealing with ranks

**Comment by DarkRaider462** [comment]
I got it to work fine with a 3rd party plugin, but the problem is now that normal players can't choose other kits even though i give them McInfected.Kits.(Kitname)

**Comment by Bimmr** [comment]
This is being added. Expect the next version within the week... Depends when i find time to stress test.
