### ISSUE TITLE
Kit NPC

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#33]
Hey,

The kitnpc plugin does nothing when you click it (both right or left click)

**Comment by Bimmr** [comment]
Are the Npc's names matching the kit's name? Is there an error? Are you using the right version of Citizens?

**Comment by alexlab963** [comment]
It actually worked after some restarts.
Another question,
Is there an option in the Ranks plugin to only disable the name tags prefixes?
I cant seem to find it

**Comment by Bimmr** [comment]
It is added in the new version coming sometime this week
