### ISSUE TITLE
API

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#34]
Hey,

Is there any API i can use to view the stats on other plugin?

Thanks in advance

**Comment by Bimmr** [comment]
This is the old wiki page that i had for the API, It may be a little outdated though
# ░ McInfected
## Getting Started
* Add McInfected.jar to your plugin's build path
* In your plugin.yml add `depend: [McInfected]` or `softdepend: [McInfected]`

## Using McInfected
`McInfected mcInfected = (McInfected)(Bukkit.getPluginManager().getPlugin("McInfected")`

Then you can use all of McInfected's managers:
* [CHandler](#chandler)
* [DisguiseManager](#disguisemanager)
* [FileManager](#filemanager)
* [KitManager](#kitmanager)
* [LobbyManager](#lobbymanager)
   * [ArenaManager](#arenamanager)
* [MenuManager](#menumanager)
* [Messanager](#messanger)
* [MySQLManager](#mysqlmanager)
* [ScoreSystem](#scoresystem)
* [Settings](#settings)
* [**Events**](#events)


## CHandler
With CHandler you can manage the commands within Infected. For example if you wanted to add a command you just create a new class that extends SubCommand and then you register it in the CHandler. For an example on this, just take a look at the code [Here](https://github.com/Bimmr/McInfected-Shops/blob/master/src/me/bimmr/mcinfectedshops/ShopCommand.java)

## DisguiseManager
With DisguiseManager you can check if the player is disguised or you can manually disguise and/or undisguise them yourself.

## FileManager
With FileManager you have full control over every McInfected file. You can use this to set/get values from any of the files

## KitManager
With KitManager you can control the kits that McInfected uses. You can create your own, get the already in game kits, or delete/unload some.

## LobbyManager
LobbyManager is  one of the most used things within Infected, when ever a piece of code needs to see the gamestate or if a players in a game you just use the lobby manager.

### ArenaManager
The ArenaManager is within the Lobby class, this allows for every lobby to have it's own group of arenas. The way you access the arena manager is through: `mcInfected.getLobbyManager().getLobby("Lobby Name").getArenaManager()`

## MenuManager
MenuManager is just the class I use to get the GUI menus.
With MenuManager there isn't much you can do, so you can probably just look at it yourself...

## Messanger
Messanger is the class all my messages go through. You can use this class to get you're own messages from the Messages.yml(Also requires the FileManager) To do this, you can just take a look at the code [Here](https://github.com/Bimmr/McInfected-Shops/blob/master/src/me/bimmr/mcinfectedshops/ShopCommand.java#L47)

## MySQLManager
MySQLManager is just what McInfected uses to get and set data into the MySQL database.

## ScoreSystem
ScoreSystem is what McInfected uses to edit a player's score with the appropriate multiplier and score.

## Settings
Settings is where McInfected gets all it's settings for... well... pretty much everything.


# Events
McInfected has a few events that you can listen for:
* **McInfectedDeathEvent**--Called before a player dies
* **McInfectedEquipEvent**--Called before a player gets equipped
* **McInfectedInfectEvent**--Called before a player gets Infected
* **McInfectedJoinEvent**--Called before a player joins the game
* **McInfectedLeaveEvent**--Called before a player leaves the game
* **McInfectedReloadEvent**--Called before McInfected reloads
* **McInfectedResetEvent**--Called when a player gets their info reset (Normally used when a game ends and the player goes back to the lobbby)
* **McInfectedRespawnEvent**--Called before a player respawns
* **McInfectedRestoreEvent**--Called before a player gets restored to before they joined
* **McInfectedTimerEvent**--Called when the timer switches the gamestate

**Comment by alexlab963** [comment]
Hey,

Thanks :)

Also, i will buy Mcingected LeaderBoards (in a few minutes) can you make it like leaderboards so it shows the player head?

**Comment by Bimmr** [comment]
It already supports it, i just kinda forgot to write that on the page...Just put the head above the block the sign is on.

**Comment by alexlab963** [comment]
Alright thanks again :)

**Comment by Bimmr** [comment]
Let me know if it causes any performance issues. It's still in beta so I'm not to sure how it works under stress.
