### ISSUE TITLE
Kits [REQUEST]

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#35]
Hey,

Could you add an option to give extra items on every kit based on permissions?

Permission example mcingected.item.<item>.<amount>
And they would get that item no matter their current kit

**Comment by Bimmr** [comment]
Just create multiple versions of the kit and remove permissions for the
kits they cant use.

**Comment by alexlab963** [comment]
Hey,

I am gonna have 26 kits, and i want to add 10 different items, that would be 260 kits in total...

Cant you do it please?

**Comment by Bimmr** [comment]
Sorry, i would have to almost redo the kits system for it
