### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#36]
Hey,

I have all your plugin for mcinfected, and i only have one lobby so all player go to it when connected
I have set the required players to 1 on the only arena and even though we are 2 online and both voting for the same map, the game doesnt start

I have to do /mcinfected admin start <lobby> to go to the voting phase but we have already voted

**Comment by Bimmr** [comment]
Try setting the required players to 2, as it is working for me. Also check the console for any errors.

**Comment by alexlab963** [comment]
I had try with 2 but nothing happened

**Comment by Bimmr** [comment]
And theres no errors?

**Comment by Bimmr** [comment]
Just tested it again and its working for me.

**Comment by alexlab963** [comment]
Nope, no errors

**Comment by alexlab963** [comment]
Here is my config http://pastebin.com/WMkNhauD

**Comment by Bimmr** [comment]
Change Global.Game.Auto Start to 2... currently you have it saying to wait
for 4 players

**Comment by alexlab963** [comment]
Opps....

That is the biggest mistake i have ever made :p 
I had never see that option:(
