### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#38]
I found a few bugs
Players can hit each other while infecting, the zombies cannot infect
Also if zombies die by physics (or just randomly) they are not disguised as zombies anymore

**Comment by Bimmr** [comment]
Ill look into the first 2 but the disguise issue would be the disguise plugin because i dont undisguse them.

**Comment by alexlab963** [comment]
Alright thanks, i will let you if i find anything esle.

**Comment by alexlab963** [comment]
How is it going?

**Comment by Bimmr** [comment]
Im on holidays for another week.

**Comment by Bimmr** [comment]
Uploaded a fix for it. I decided to just look into it so i knew how i was going to fix it, and noticed that McInfected was ignoring all damage if the server had Crackshot on it...

**Comment by Fireflies** [comment]
Most plugins plugins undisguise on death, all you have to do is re-apply the disguise.

**Comment by Bimmr** [comment]
This issue should only be in this version; It had a bug where the player
actually dies when they get hurt instead  of stopping before they get
killed. So this bug shouldn't be there anymore.
