### ISSUE TITLE
Player Interact permissions

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#39]
Hey, 

Could you add permissions to allow players to interact with blocks & mobs while in lobby and game?
I need them to open some levers, press buttons and kill some cows for food

**Comment by Bimmr** [comment]
They can interact with blocks if you enable it. And i wont be adding
anything to make them able to kill mobs  in the lobby as you should be able
to already.

**Comment by alexlab963** [comment]
Where is the option to enable it?

**Comment by Bimmr** [comment]
In the config

**Comment by alexlab963** [comment]
I know that, i cant find something to let players interact with blocks

**Comment by Bimmr** [comment]
What blocks... anything that can be interacted with triggers a bukkit event
and that is what i watch.

**Comment by alexlab963** [comment]
ohh , Okay thanks
