### ISSUE TITLE
Kits Bug and player infected addition

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#40]
Hey,

With the new version i dont get the kits displayed, there are no error in the console it actually shows a message for every kit saying that it is loaded

Also could you make it so players get infected if the die by mob zombies?
And prevent infected from killing the the zombies? (not cows, pigs, sheep etc)

**Comment by Bimmr** [comment]
Ill look into the kits but when a player dies they should get infected. And
just stop other mobs from spawning as i dont see a reason to even have mobs
in a McInfected arena

**Comment by alexlab963** [comment]
Have you found anything?

Also can you add 2 options to the dedicated addon?
1) Allow players to choose kit even when they are not in a lobby
2) Have the lobby-items when they not in a lobby

**Comment by Bimmr** [comment]
The first one can be done by changing the time allowed to change kits after
death in the config, and I won't be adding the second one as they are lobby
items and I don't see a reason you would need them outside the lobby

**Comment by alexlab963** [comment]
But they wont even play while not in a lobby...

**Comment by Bimmr** [comment]
The dedicated add-on forces the players to join a setup and playable lobby
on joining the server

**Comment by alexlab963** [comment]
kk,
Is there a fix update coming for the kits problem?

**Comment by Bimmr** [comment]
Like I said before, I am currently on vacation. These github issues just go
through my email

**Comment by Bimmr** [comment]
Kits are showing up for me.

**Comment by alexlab963** [comment]
well i cant see them, the  kits configuration is fine could you come on the server and check? 77.111.208.40:25565

**Comment by Bimmr** [comment]
Turned out to be a permissions issue not liking '+' being in the kits' name.
