### ISSUE TITLE
McInfected Ranks

### ISSUE THREAD

**Issue by alexlab963** [Bimmr/McInfected#45]
Hey,

When people join no matter of what permissions i have set on the ranks config they have all the kits, this is fixed once i set the rank manually.
Ex a player joins at the default rank but has all the kits, if i do /mcinfected admin rank <player> default he has only the kits i have set

**Comment by Bimmr** [comment]
Go into the config and disable seeing all the kits l. I wonder if that's
causing the issue

**Comment by alexlab963** [comment]
No, that changes nothing

**Comment by Bimmr** [comment]
Can you send me your permissions file and the name of the permissions plugin you're using as well as your Kits.yml and Ranks.yml?

**Comment by alexlab963** [comment]
Sure, i will send them on spigot

**Comment by Bimmr** [comment]
What I did:
- Made sure Vault was installed
- Made sure "Permissions By Default.Kits" set to false in the config

And it seemed to work perfectly for me.

**Comment by Bimmr** [comment]
And it just occurred to me that it says no where on any of the pages that this feature requires Vault...

**Comment by alexlab963** [comment]
I do have vault and "Permissions By Default.Kits" set to false but this is still happening on player join

**Comment by Bimmr** [comment]
Oh, another thing I did was remove all the user permissions in the permissions.yml

**Comment by Bimmr** [comment]
https://www.youtube.com/watch?v=uijTwgON1ZM&feature=youtu.be

**Comment by Bimmr** [comment]
Just tested with the files you sent me without editing a single thing and it worked for me. So it may be the fact that there are users being saved in your permissions.yml with permissions that shouldn't be there.

**Comment by alexlab963** [comment]
Its okay now , i got it to work after removing the user/per world permissions on my permission plugin

**Comment by Bimmr** [comment]
K, if those permissions show up again just tell me cause t would be a bug I need to try and figure out why they're showing up.
