### ISSUE TITLE
Inventory gets hidden when leaving game

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#46]
When you join and then leave a lobby you lose your inventory... but if you leave and join the server you have the inventory back, idk what the problem is. 

You can try it in my server lasvalkirias.com  > Arcadia portal

I use Multiverse-Inventories, idk if that affects it. will try it but, it only happens with McInfected i have others games that dont "hide" the items.

**Comment by Bimmr** [comment]
Fixed in 1.2.5
