### ISSUE TITLE
Signs Problem

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#50]
I decided to move my lobby and ofc i had to remake the join sign.

this happened after restart
http://hastebin.com/ejesenacow.avrasm

the sign worked until i restarted the server.

**Comment by Bimmr** [comment]
Wrong hastebin link?

**Comment by Blackyvk** [comment]
lol sorry, didnt even send the log, fixed...

**Comment by Bimmr** [comment]
When you removed the signs did you break them with your hand or with a plugin? Because the error is saying that signs were not removed right so you'll have to go into the Signs.yml or the Lobbys.yml and remove the sign from the file.

**Comment by Blackyvk** [comment]
hand and then i tried to remove the whole Signs: on the yml, recreated the file 

got this

  Signs:
    Information:
    - Infectados,-344,61,468,0.0,0.0

and doesnt work

**Comment by Bimmr** [comment]
You will have to remove that part of the Lobbys.yml while the server is off in order to remove the error. Although this issue has been fixed in 1.2.6(No ETA)
