### ISSUE TITLE
Could not pass event PlayerInteractEvent to McInfected-CustomSigns v0.0.2

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#52]
http://pastebin.com/wp5RiYfB

Happened after updating to lastest Infected, I cannot use the signs. I tried recreating the signs.yml didnt work.

**Comment by Bimmr** [comment]
Are you sure the lobby sign is still showing the info for the right lobby?

**Comment by Blackyvk** [comment]
fixed in 0.0.3 custom signs.

**Comment by Blackyvk** [comment]
http://pastebin.com/5YbeHBXs

worked first time then after a restart error again...

**Comment by Bimmr** [comment]
Yeah, I'll have to look into it because thats saying that no valid lobbies
are found

**Comment by Bimmr** [comment]
Turns out it was another plugin causing the issue. Closed
