### ISSUE TITLE
McInfected - Returning players to /spawn hub

### ISSUE THREAD

**Issue by OliverCraft** [Bimmr/McInfected#53]
I am having an issue when players are killed in the McInfected arenas, they are being sent to our primary hub at /spawn.  No one is being sent to the arena lobby to restart.  And furthermore, they are no longer considered in-game by McInfected, but they do still have the scoreboard on screen.  The only resolution is to issue the command '/mcinfected admin reload'  which is not right.  Any fixes or suggestions?  Thank you for your time!

**Comment by Bimmr** [comment]
Turn on debug mode and run a game then send me the log. Im also going to
assume that there is no error in your console as you never said there was
one.

**Comment by OliverCraft** [comment]
Mind enlightening me on the method for turning on debug mode?  And yes, no errors in console!

**Comment by Bimmr** [comment]
In the config theres a setting called "Debug" just set that to true

**Comment by OliverCraft** [comment]
Well, nothing posts directly to my server log files that I am seeing.  But directly to my console, this spam is happening:

http://pastebin.com/SESNzK5g

**Comment by Bimmr** [comment]
What happens before that message spams

**Comment by OliverCraft** [comment]
Once we join the lobby (which is on the same map as the arena), the ClassCastException starts spamming.  If I kill the other player, they are sent back to /spawn and them issuing the command '/mcinfected join' says 'you are already in a game'.  While still in the game, I myself type the command '/mcinfected leave' and it says I am not in a match, although I am still on the map since I didn't die.  And we both have the scoreboard active and the problem only goes away with me issuing as an op the following command: '/mcinfected admin reload'.  Obviously, the issue occurs every time the game is launched.

**Comment by OliverCraft** [comment]
I have even disabled all other plugins to ensure nothing is conflicting.  I am running Spigot version 1.8.8 R.01 Snapshot if that helps.  You are welcome to swing by the server for direct troubleshooting if need be: OLIVERCRAFT.MCSERVER.WS

Thank you again for your time and hard work!

**Comment by Bimmr** [comment]
Can you send me your McInfected folder? I'd recommend sending it over
Spigot if you don't want people to take your Kits.yml

**Comment by OliverCraft** [comment]
Kits are still default so I don't care if they take them!

Compressed folder here:
http://www.mediafire.com/download/q7mq44oh4q7mqx1/McInfected.zip

**Comment by OliverCraft** [comment]
Bump

**Comment by Bimmr** [comment]
Do you have any addons running?

**Comment by Bimmr** [comment]
On the bottom of the screen do your players have the actionbar? (Message above the armor) It says what team they're on.

**Comment by OliverCraft** [comment]
No add-ons for McInfected running nor installed.

**Comment by OliverCraft** [comment]
Sorry I missed when you came on.  I had the plugin disabled, because it
crashes my server when I issue a /reload command from in game.  Without it
enabled, the crash never happens. It is enabled now if you'd like to
troubleshoot.

The only bottom bar my players have is the countdown to game end with the
normal hearts and hunger as well as the right side stat bar.

**Comment by OliverCraft** [comment]
So running this plugin on my home server it ran fine with nothing added. I
added all plugins from my normal server, and I was getting messages you
can't injure defenseless players. I disabled WorldGuard plugin and the game
started working again. Any suggestion to accommodate WG, as this is
essential for a public server.  Until I hear from you, I'm going the try
the pvp allow flags on the WG region. Any other suggestions please inform!
Thanks,

**Comment by Bimmr** [comment]
Try disabling what ever it is in worldguard that prevents you from
attacking defenceless  players

**Comment by OliverCraft** [comment]
I fixed the problem!  For future reference, folks running WorldGuard will
need to define a region on the McInfected map/s and add PVP ALLOW flag to
that region for the map!  Thank you so much for your help! I'm off to give
you 5 stars right now!!
