### ISSUE TITLE
Returning to spawn

### ISSUE THREAD

**Issue by OliverCraft** [Bimmr/McInfected#54]
So my players are still being returned to spawn on death.  Which would be Multiverse default spawn world.  This much I have confirmed.  Any way to fix this?

**Comment by Bimmr** [comment]
Mcinfected  should be stopping them before they die so one of the plugins
on your server are overwriting  what mcinfected does. Id start on a fresh
server and keep adding plugins 1 by 1 till you find out which one is
causing the issues.

**Comment by OliverCraft** [comment]
Multiverse controls where players spawn on death and WorldGuard might have
a flag that I'm not aware of. Would you still be interested in looking at
the plugins folder? I can't seem to eliminate this issue either way

**Comment by Bimmr** [comment]
If you can send me a zip of your plugins folder i could do some testing

**Comment by OliverCraft** [comment]
Here is my plugins folder. I removed the PEX files as I don't think you
need those. If you do, then lmk please!

Link here:
https://www.mediafire.com/?bjtwmivsfr2ibd6

**Comment by Bimmr** [comment]
I had to remove the link after I downloaded because you had some premium plugins in there I think

**Comment by OliverCraft** [comment]
Yes I do. Do you need another link?

**Comment by Bimmr** [comment]
No, because I downloaded it before I removed the link

**Comment by OliverCraft** [comment]
Ok good. I forgot the ticket was public lol

**Comment by Bimmr** [comment]
I'm not going to be able to test your plugins on my local server as the server makes my computer very laggy, my only suggestion is to try adding the plugins to a server one by one until you figure out which one is breaking McInfected, I'd suggest to try without any other minigames on the server first.

**Comment by Bimmr** [comment]
Closed, another plugin would be causing this to happen.
