### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#55]
Hi !

Could you add translations for this messages : 

http://i.imgur.com/mMoerrI.png (Scoreboard)

http://i.imgur.com/qnlwNN3.png (Scoreboard & "human" or "zombie")

Thanks :)

**Comment by Bimmr** [comment]
Can't make any promises as I only work my plugins on the weekend and that would be something I'd add once I get around to redoing the way scoreboards work

**Comment by JohOply** [comment]
I will wait for it, your work is nice ;)

**Comment by JohOply** [comment]
Others : http://i.imgur.com/LYfZ7B3.png

And i have a request : for name of arenas in vote GUI, can you change each "_" to " " (blank), like in addon LobbyItems ?

**Comment by Bimmr** [comment]
I added replacing "_" to " ", but changing the text in the menu is something that I will have to add later.

**Comment by Bimmr** [comment]
Anything else you can think of that you'd want to be able to translate?

**Comment by JohOply** [comment]
To choose the kit (Human and Zombie), there is "current" on the top : http://i.imgur.com/GiMvBym.png

For now, i think i give you all info with my screens, i didn't see anything else

**Comment by JohOply** [comment]
I have found this scoreboard :) http://i.imgur.com/ho4l5PE.png

**Comment by Bimmr** [comment]
I've updated the scoreboard class, but the translations will have to come in the next update.

**Comment by Maxetto** [comment]
I subscribe to this. Hope It gets 100% translatable. I would report also other points where "_" should be changed to " ", such as Ranks and Kits names.

**Comment by Bimmr** [comment]
Can you show examples of where "_" are that you want changed?

**Comment by Maxetto** [comment]
Like Kit names:
![2016-02-13_22 15 04](https://cloud.githubusercontent.com/assets/1360752/13030094/76a8596a-d29f-11e5-8b4e-399681ea4b00.png)

**Comment by Bimmr** [comment]
Next version will have it changed. Let me know if theres anything else.


McInfected-Dedicated's messages reset on server restart --- Little note to remind myself.

**Comment by Maxetto** [comment]
Also Rank names:
![2016-02-15_00 56 27](https://cloud.githubusercontent.com/assets/1360752/13037355/41e9b10c-d37f-11e5-961b-071a4a5ced84.png)

**Comment by Bimmr** [comment]
Everything posted is translatable/replaced "_" with " "
