### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by OhKawaii** [Bimmr/McInfected#58]
Getting errors in console.
No messages are showing up in the help/setup page.

http://pastebin.com/8BLg9tqx

**Comment by Bimmr** [comment]
Are you using Spigot? If not then the plugin will not work.

**Comment by Bimmr** [comment]
Just looked at the error again, what version of McInfected are you using? Because if it's having to use reflection then you're not using the newer version.

**Comment by Bimmr** [comment]
Why report a bug if you have no intention of responding to messages...
