### ISSUE TITLE
Max Players doesn't work

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#59]
Hi

Option "Max Players: x" doesn't work in 1.2.8 :)

**Comment by Bimmr** [comment]
Apparently I never saw this ticket... 10 days ago.... I'll look at it this weekend.

**Comment by Bimmr** [comment]
In what aspect does it not work? Does it stop them at one more that the max players, or does it just not stop them at all.

**Comment by JohOply** [comment]
In my case, I put max limit to 15 on a map, but there was 18 players on it

**Comment by Bimmr** [comment]
That's odd... I just tried it set to 2, and I wasn't able to have a 3rd player join.

**Comment by JohOply** [comment]
Maybe there is a difference between your version and the release that i use ? (1.2.8)

I will try it again if i have some times ;)

**Comment by Bimmr** [comment]
Would you want to beta test the new version of McInfected?

McInfected 1.2.9
- Cleaned up the MySQLManager class
- Fixed leave locations
- Fixed bug when last human leaves and game doesn't end
- Can now disable/enable the constant actionbar
- Fixed /McInfected Stats <Name>
- Fixed a possible error if no arenas can be voted for
- Fixed a bug in ItemUtil related to the leather
- Eating food now heals you
- Changed up the way the setup command works
- Removed blank line above messages when you perform a command
- Finally got around to updating the Scoreboard system
	- New Event system
	- Configurable Titles
	- Line limit is now 48
	- Runs smoother

**Comment by JohOply** [comment]
Maybe, why not ;) I didn't got the time to try again problem about max players for now

**Comment by Bimmr** [comment]
I'll message you over Spigot when i get home.

**Comment by Bimmr** [comment]
Should be fixed in the newest uploaded version.
