### ISSUE TITLE
Each command display an empty line

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#60]
Hi,

A lot of commands (/inf leave, /inf vote, /inf kit and maybe others) display an empty line into the chat. For instance : https://i.imgur.com/kGopEps.png

I use 1.2.8.

**Comment by Bimmr** [comment]
The empty line is in there to make the message stand out when it gets displayed.

**Comment by JohOply** [comment]
Can you add an option to disabled it ?
