### ISSUE TITLE
SQL errors in log

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#61]
Had this in my log, one player wasnt able to die once but i dont know if its related.

http://hastebin.com/pihayeweja.avrasm

http://hastebin.com/ifesuwaner.profile

**Comment by Bimmr** [comment]
Non of those links are working for me.

**Comment by Blackyvk** [comment]
try here http://pastebin.com/8hyY7PUh

**Comment by Bimmr** [comment]
Ya, those links work. Ill have to look at it next weekend.

**Comment by Bimmr** [comment]
Would you want to beta test the new version of McInfected?

McInfected 1.2.9
- Cleaned up the MySQLManager class
- Fixed leave locations
- Fixed bug when last human leaves and game doesn't end
- Can now disable/enable the constant actionbar
- Fixed /McInfected Stats <Name>
- Fixed a possible error if no arenas can be voted for
- Fixed a bug in ItemUtil related to the leather
- Eating food now heals you
- Changed up the way the setup command works
- Removed blank line above messages when you perform a command
- Finally got around to updating the Scoreboard system
	- New Event system
	- Configurable Titles
	- Line limit is now 48
	- Runs smoother

**Comment by Blackyvk** [comment]
yeah np but, I doubt i will find people online tonight lol

**Comment by Bimmr** [comment]
Should be fixed in the newest uploaded version.
