### ISSUE TITLE
Enchantment 

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#62]
When i have a kit with this item:
    - item:STICK enchantment:19 enchantment:16 name:Kick_Stick

I will set higher the enchantment level like Sharpness 2, but how?
please answer me :)

**Comment by Bimmr** [comment]
https://github.com/Bimmr/McInfected/wiki/McInfected---Wiki-Home#items

**Comment by MacTirom** [comment]
Thx.
