### ISSUE TITLE
Why eating in the Human Kits?

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#64]
I have a question. Why are in the standard human kits Melon's... ?
I think with this can i heal me but its don't work.

**Comment by Bimmr** [comment]
There was an addon that I made that made food heal when you ate, but I ment to add it to McInfected, and i'm thinking I forgot to add it.

**Comment by MacTirom** [comment]
When add you than this? :D

**Comment by Bimmr** [comment]
Working on it right now, but the update won't be for a while. I got a lot of things I need to test with it before I upload it.

**Comment by MacTirom** [comment]
Ok ;)

**Comment by MacTirom** [comment]
me the way I'm sorry for my bad english, I'm German: D

**Comment by Bimmr** [comment]
Added to McInfected, will be in the next update.
