### ISSUE TITLE
Game not ending properly

### ISSUE THREAD

**Issue by CaptnSisko** [Bimmr/McInfected#65]
I have the default config, I only changed armor color and require empty inventory. I noticed once everyone is infected, the game does not end. The game only ends if time runs out or a zombie commits suicide. Because my map is a sky map, this is generally achieved by jumping into the void.

This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

I don't think I have any errors in the logs.

**Comment by Bimmr** [comment]
Well double check that there are no errors in the log, because there should be an error if this is happening.

**Comment by CaptnSisko** [comment]
![screen shot 2016-01-04 at 6 54 35 pm](https://cloud.githubusercontent.com/assets/16022847/12103952/b097bea4-b314-11e5-9ced-d9eab4c06bff.png)
The only error was from my failed attempt to change the kits.

I noticed that sometimes the game ends correctly. I do not know what triggers this.

**Comment by Bimmr** [comment]
Can you send me what you have in your edited Kits.yml because you're doing something incorrectly.

**Comment by CaptnSisko** [comment]
The error occurred with the default kits. I do not have the edited kits because I deleted kits.yml to have the plugin regenerate the default kits.

I think it may have something to do with people falling into the void, as that would explain why nobody has seen this error before.

Another thing I noticed is that the human/zombie counter doesn't refresh until you crouch.

If I had to take a guess about what's wrong, I would say that the plugin only checks if all the players are zombies if a zombie dies. Evidently, it does not preform the same check when a human is converted into a zombie.

These are all my assumptions based on my limited java knowledge. I really have no clue.

**Comment by Bimmr** [comment]
I just tested with falling into the void, but the game ended properly for me. If you do get this issue again check the console because there should be an error.

**Comment by CaptnSisko** [comment]
Updating libsdisguises and protocallib seems to have fixed it... I don't know how though.

**Comment by Bimmr** [comment]
Huh, kinda odd how thats all the issue was, but as long as its all working
now.

Closed #65 <https://github.com/Bimmr/McInfected/issues/65>.

—
Reply to this email directly or view it on GitHub
<https://github.com/Bimmr/McInfected/issues/65#event-506466865>.
