### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#67]
Idea for a feature :D 
Only a idea ^^

A bottle (Zombie healing)

When i shot this of a zombie is it a Human ! Effect is also healing the Zombie from the Virus! And its function only by the zombies there infected. Not the Mother Zombies! They can't heal! (Because very much Game bugs) ^^^

Its only a idea for you :dango:

**Comment by Bimmr** [comment]
Im not able to add this because someone requested this as a private addon a
few months ago.

**Comment by MacTirom** [comment]
Ok ^^
