### ISSUE TITLE
The Setting Players

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#69]
The Setting Players in the config:  Allowed To Join Started Games: false
Don't work i set it on false and the Players can join. The same with the setting Allowed To Join Started Games: true

:/

**Comment by Bimmr** [comment]
I'll look into it.

**Comment by Bimmr** [comment]
I'm not able to add this feature due to the current way everything in McInfected is setup. If you really need this feature in McInfected, then please make a new ticket.
