### ISSUE TITLE
Class Signs

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#77]
Question. I will adding a sign with the you can choose a specific class. Rightclick like
/class human Berserker 
With this command i can choose directly the class. "You've choosen Berserker as your Human kit.
Also i add this command on the sign like:
1 Line: [McInfected]
2 Line: [Command]
3 Line: Class Human
4 Line: Berserker

But this doesn't work! I always reaching the human entire class selection.
Thx for a answer! :+1:

**Comment by Bimmr** [comment]
I'll look into it when i get time.

**Comment by Bimmr** [comment]
Fixed in 1.3.2
