### ISSUE TITLE
Hoou i have a good Idea for you :D

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#80]
A Test Server like the Plugin "Village Defense" They have on the Spigot Site a Test Server
Here: Try it yourself at PLAY..........

You can add this with my McInfected Server. Then he is not so popular :/
And i swear it is only a McInfected Server you can test him

When you are interested (its a good idea for you and me).
You can help my Server with YOU Plugin and i help you on your Plugin Site.
I can add on the Website (yes the Server has a Website) Link: http://infectcraft.de/

It is a good and professional Server.
And we would both get something off of it. :100:

**Comment by Bimmr** [comment]
Already tried this type of thing 2 times, both times the server stopped suddenly.
