### ISSUE TITLE
Mcinfected Error

### ISSUE THREAD

**Issue by MERRYACS** [Bimmr/McInfected#81]
1.i can't run on craftbukkit or on spigot, when i typing mcinfect it show:

![qq 20160409120743](https://cloud.githubusercontent.com/assets/17223128/14401676/be869490-fe4b-11e5-8830-ad5faafb774a.png)

**Comment by Bimmr** [comment]
I might just need a little more information than "It doesn't work". Maybe you can try posting the error that occured.......

**Comment by MERRYACS** [comment]
I found out, it work on paperspigot.

**Comment by MERRYACS** [comment]
BUT the glitch is still occur, when player disconnect the server and rejoin will show:
![image](https://cloud.githubusercontent.com/assets/17223128/14550018/b4b95ca8-02f7-11e6-9c47-3e6ce9fc3f41.png)

**Comment by MERRYACS** [comment]
there only 3 players in this server, and the scoreboard show there is total 4

**Comment by MERRYACS** [comment]
so it won't end unless the ''ghost player leaving''

**Comment by MERRYACS** [comment]
HI....

**Comment by MERRYACS** [comment]
HI??

**Comment by Bimmr** [comment]
Check McInfected's Spigot discussion page.

**Comment by Bimmr** [comment]
Not able to replicate this bug on the latest McInfected, if it occurs again please repost it.
