### ISSUE TITLE
Tablist + Scoreboard incompatibility

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#84]
i'm using   ( https://www.spigotmc.org/resources/tablist-prefix-1-9.7576/ ) It lets me add nametags and colors to  users in the tablist based on permissions.

When you join a mcinfected arena, the tablist goes all white (which i belive it happens with every plugin that uses the scoreboard), this isnt bad, the problem is when you stop playing mcinfected, the tablist stays white, when it should restore the other plugin format.

**Comment by Bimmr** [comment]
Try removing McInfected Ranks, and let me know if that fixes it. Because i'd imagine that the issue is the team's prefixs

**Comment by Blackyvk** [comment]
I'm not using the ranks plugin, just lobby items, customsigns.

**Comment by Bimmr** [comment]
hmm, odd. Not sure why it would be affecting it then. I'll have to play around with it when my computer accepts Java as being installed....

**Comment by Blackyvk** [comment]
it's the scoreboard, whatever plugins modifies the scoreboard messes with the nametags and the tablist.
