### ISSUE TITLE
Crackshot  and Armor Kits are Incompatible

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#85]
CrackShot version: 0.98.5
ProtocolLib version: 4.0.1-b291
Spigot 1.9.4
EssentialsX version: 2.0.1-b345

I found that all the items from my kits were gone except for the weapons, crackshot + vanilla weapons

And when I try to add for example a Helmet
/McInfected setupnf Kit Civil Helmet Set

It stays null

If i remove crackshot, it works perfectly, but thats not the idea ;D, no guns no fun.

**Comment by Bimmr** [comment]
Crackshot will not bug out the game in the next version.
