### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by caxerx** [Bimmr/McInfected#87]
I got Error when connecting to MySQL Server
[https://dl.dropboxusercontent.com/u/91473899/mc/temp/MCINF_Err.png](https://dl.dropboxusercontent.com/u/91473899/mc/temp/MCINF_Err.png)

There are the full log:
[http://pastebin.com/EsBYptNm](http://pastebin.com/EsBYptNm)

My Config:
[http://pastebin.com/BqAuKKeX](http://pastebin.com/BqAuKKeX)

I'm using
Spigot 1.10
McInfected 1.4.1
BimmCore 0.0.5

MySQL Server is reacheable
[https://dl.dropboxusercontent.com/u/91473899/mc/temp/SQLSuccess.png](https://dl.dropboxusercontent.com/u/91473899/mc/temp/SQLSuccess.png)

**Comment by Bimmr** [comment]
Was McInfected 1.4.X the first version of McInfected you used? Or did you use an older version before.

**Comment by caxerx** [comment]
I am using 1.4.1 the latest version.

**Comment by Bimmr** [comment]
I mean before, did you ever have a version of McInfected on your server
that wasn't 1.4.X

**Comment by caxerx** [comment]
Oops, Sorry.
I tried in a new server with a empty database.

**Comment by Bimmr** [comment]
So a different version of Mcinfected created your database? I was just
wondering if the code I put in the 1.4.x version to verify the table was
there messed something up

**Comment by Bimmr** [comment]
Were you actually connected but McInfected just said you weren't? (Were stats being loaded and saved?)

**Comment by caxerx** [comment]
I haven't test creating the table by old version yet.
But the table was created after connect but no data is saved.
