### ISSUE TITLE
Damage value display in the console

### ISSUE THREAD

**Issue by Akasa419** [Bimmr/McInfected#88]
When I shoot something (such as, player or creatures...) with Crackshot's gun
The damage value will display in the console....
For Example:
My Gun Have 50 Damage , Then I use it to shoot a player 3 times, and the console will show up this message:

> [23:10:46] [Server thread/INFO]: 50.0
[23:10:47] [Server thread/INFO]: 50.0
[23:10:47] [Server thread/INFO]: 50.0

Is there any solutions to stop it? Because It is annoying,
every time when I play McInfected with my friend
My console will spam by the damage value.So Please help me....Thank you

**Comment by Bimmr** [comment]
Fixed in the next version of McInfected
