### ISSUE TITLE
Advanced Achievements

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#90]
Theres is a "bug" with [advanced achievements.](https://www.spigotmc.org/resources/advanced-achievements.6239/)

If we have experience achievements, and you join a Game, the  timer wich is the exp  bar gives all the achievements from lvl 1 to 300  or more if the timers is higher.

This doesnt happen if the plugin is disabled in mcinfected world, but if for any reason you get bugged and leave the world and join another one that has the plugin active, it gives you the achievement....

I got 2 errors you might know or not just in case http://pastebin.com/5G4ZTvUd
Spigot 1.9.4

Any eta for the next version ? thanks! no hurry just wondering.

**Comment by Bimmr** [comment]
You'll have to talk to the author of that plugin. McInfected uses the
players level to show how much time is left in the game. There's probably a
way to remove the achievements for levels. As for the error it's what ever
your chat plugin is

   1. [07:18:18] [Server thread/WARN]: java.lang.NullPointerException
   2. [07:18:18] [Server thread/WARN]:    at
   mineverse.Aust1n46.chat.listeners.PacketListener.onPacketSending(PacketListener.java:64)

**Comment by Blackyvk** [comment]
what about a way to disable the  timer inside mcinfected config, or is too much trouble?

also, in the log I left there is one in the end about something different

http://pastebin.com/4NUrfnbz.
