### ISSUE TITLE
Server Casued heavy lag while Mcinfected Gaming

### ISSUE THREAD

**Issue by eric2788** [Bimmr/McInfected#92]
while mcinfected game was waiting in lobby, anything fine;but when game started, it caused a heavy delay ,
here's the timings: https://timings.aikar.co/v2/?id=561f29a6fa754e53809ac3295321c328
SQL is enabled
my plugin list
https://gyazo.com/1a94debbe895da7ceb4b93053d82441f
the lag still happening when removed mcinfected-ranks and disable SQL
https://timings.aikar.co/v2/?id=d6814d6fcd254915bb785bc5b94a5d0e&section=lag

**Comment by Bimmr** [comment]
Timings no longer exists, if the issue is still happening please create a new ticket with the timings.
