### ISSUE TITLE
ETA on 1.10?

### ISSUE THREAD

**Issue by DeathJusty** [Bimmr/McInfected#93]
I used to use this plugin when it was free and thought it was the best. I was considering buying it but saw there is no 1.10 version? do you have an ETA on the release for that?

**Comment by Bimmr** [comment]
Soon, just doing final testing.... and yes I know you posted this 20 days ago...

**Comment by DeathJusty** [comment]
Don't worry about not replying right away, we all gotta stop for life some time :D

**Comment by DeathJusty** [comment]
I saw on the spigot page but i thought id get confirmation. Has this been updated to 1.10? if so i will buy it very soon :)

**Comment by Bimmr** [comment]
Yes, it is for 1.10

**Comment by DeathJusty** [comment]
Alright sweet
