### ISSUE TITLE
crash when the vote ended

### ISSUE THREAD

**Issue by ken147** [Bimmr/McInfected#97]
com.bimmr.mcinfected.Arenas.ArenaManager.getValidArenas(ArenaManager.java:95)

> [00:00:05] [Spigot Watchdog Thread/ERROR]:        com.bimmr.mcinfected.Lobbys.Timers.getMostVotedArena(Timers.java:105)
> [00:00:05] [Spigot Watchdog Thread/ERROR]:        com.bimmr.mcinfected.Lobbys.Timers.access$5(Timers.java:84)
> [00:00:05] [Spigot Watchdog Thread/ERROR]:        com.bimmr.mcinfected.Lobbys.Timers$5.run(Timers.java:478)
> [00:00:05] [Spigot Watchdog Thread/ERROR]:        org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTa

**Comment by Bimmr** [comment]
Can you send me your Arenas.yml

**Comment by ken147** [comment]
I don't have Arenas.yml
Just have Lobbys.yml

CSGAME:
  Location: csgame,87,6,-15,-232.64984,69.450005
  Arenas:
    "MAP1":
      Icon: item:AIR
      Min Players: 2
      Max Players: 32
      Spawns:
        Zombies:
        - csgame,-55,4,350,-96.45068,-22.500044
        - csgame,-51,4,338,-156.75073,5.8499575
        - csgame,-62,4,331,-226.20068,11.699958
        - csgame,-75,4,337,-300.90094,12.899955
        - csgame,-84,7,323,-187.05121,30.449947
        Humans:
        - csgame,-40,17,341,-41.251465,22.199945
        - csgame,-39,27,325,-149.40161,21.449942
        - csgame,-56,4,324,-319.05188,15.899947
        - csgame,-84,4,343,-322.0515,10.4999485
        - csgame,-88,7,363,-344.2517,18.299948
        - csgame,-87,13,359,-203.40198,23.250004
        - csgame,-63,17,368,-87.60254,28.200008

**Comment by Bimmr** [comment]
Can you send me your actual Lobbys.yml file? I need the formatting in order to actually test it

**Comment by ken147** [comment]
the problem is fixed
It happened if i just have 1 arena for the lobby

**Comment by Bimmr** [comment]
Thanks for finding that, I'll look into it a bit more

**Comment by Bimmr** [comment]
I did fix this a bit ago in the dev version... Just forgot to close.
