### ISSUE TITLE
How can I set different health for different kits?

### ISSUE THREAD

**Issue by ken147** [Bimmr/McInfected#98]
I want to make the health higher
Also can you add the attributes operation in  kit's items
Such as MaxHealth  Knockbackresistance

**Comment by Bimmr** [comment]
id:Stone_Sword data:100 name:&5Sword lore:This|Is|Sparta color:150,5,100 attribute:ATTACK_SPEED,MAIN_HAND,10,ADD_NUMBER";


attribute:<[attribute name](http://bimmr.github.io/BimmCore/me/bimmr/bimmcore/items/attributes/AttributeType.html)>,<[slot](http://bimmr.github.io/BimmCore/me/bimmr/bimmcore/items/attributes/Slot.html)>,<value>,<[operation](http://bimmr.github.io/BimmCore/me/bimmr/bimmcore/items/attributes/Operation.html)>

**Comment by ken147** [comment]
1.8 can't?

**Comment by Bimmr** [comment]
No, Attributes weren't added till later in Minecraft. Just update to 1.10.2
